### ISSUE TITLE
Optional emoji rendering support

### ISSUE THREAD

**Issue by ntc2** [matterhorn-chat/matterhorn#125]
It would be nice if Matterhorn had a way to optionally to render emojis. Could use something like libcaca (https://en.wikipedia.org/wiki/Libcaca) or img2txt (https://github.com/hit9/img2txt). Imagine being rickrolled in ASCII (has been imagined before: https://github.com/keroserene/rickrollrc/)!

**Comment by jtdaugherty** [comment]
Hah. Personally I use Matterhorn because I want to *avoid* that stuff, but I suppose we could make this a config option. :)

**Comment by jtdaugherty** [comment]
I think doing this will result in:
* multi-row ASCII art versions which will not inline the same was as the original text
* ASCII art conversions that are unlikely to clearly depict the original source image

**Comment by jtdaugherty** [comment]
@ntc2 Also, it would help me to know if you are trolling. :)

**Comment by ntc2** [comment]
Not trolling, in that I would appreciate this feature if I were using Matterhorn, but I'm also not expecting to be taken too seriously :)

E.g., if someone wrote `:man_with_gua_pi_mao:`, I would not understand what they were getting at if there were no way to render it. Oh, wait, I would also have no idea what they meant if it was rendered.

And what about `:smile_cat:` vs `:smiley_cat:`? A very fine distinction that's not captured by the names.

**Comment by jtdaugherty** [comment]
> Not trolling, in that I would appreciate this feature if I were using Matterhorn, but I'm also not expecting to be taken too seriously :)

Okay. Thanks! I really couldn't tell from both the topic and the tone of the original text. :) I'm happy to leave this open and take it seriously (hence my other comments).

**Comment by aisamanra** [comment]
The built-in emoji set is I believe [pretty standard](http://www.webpagefx.com/tools/emoji-cheat-sheet/) and we could maintain a mapping from human-readable names (like `:foo:`) to emoji in the built-in set. For custom emoji, we'd have to think harder, but keeping that built-in mapping to actual code points (so we can map `:smile_cat:` to the Unicode character `U+1F638`, or 😸) is probably worthwhile.

**Comment by aisamanra** [comment]
(IIRC, `brick` still has some issues with double-wide characters, and I don't know what it'd take to mitigate those, but that'd be a prerequisite for rendering Unicode emoji characters.)

**Comment by jtdaugherty** [comment]
Yeah, that's true if we render them as unicode rather than as ASCII art. (And yes, `brick` and probably `vty` both need work to support this.)

**Comment by jtdaugherty** [comment]
(In fact the only open brick ticket is for this problem.)

**Comment by jtdaugherty** [comment]
And for what it's worth, even once `brick` and `vty` support this, `matterhorn` will need to consider it, too; there are spots where we assume that one character == one column.

**Comment by ntc2** [comment]
A potentially easy solution is to treat them like links that can be opened in the browser to see the graphic. Jason said it might be tricky to get a URL from Mattermost in some cases though (for custom emoji?).

**Comment by jtdaugherty** [comment]
We can get the URLs for custom emoji; it's all the rest that we can't get. Although if we were to render Unicode versions instead, the custom URLs don't help us. But like @aisamanra mentioned, if the bulk of them are relatively standardized then we can probably get away with using a list obtained elsewhere. Once `brick` and `matterhorn` support multi-column glyphs then we'll have what we need to make this work.

**Comment by jtdaugherty** [comment]
Okay. Now:
* `brick` supports wide characters in `0.14`
* `vty` knows about a larger collection of Unicode wide characters in `5.12`

However! This isn't the end of the story. Even if `vty` and `brick` get the right answer to "How wide is 💩?" the *terminal* still might not treat it as a two-column character. Both `Terminal.app` and `iTerm2` fail to do this. So you can still enter "💩" in the brick editor in Matterhorn and the cursor will behave *mostly* as expected, but text rendering will be hosed because of the terminal emulator. I reported this to the iTerm2 folks and we'll see what comes of it:

https://gitlab.com/gnachman/iterm2/issues/5323

I'd also be interested to know how well this works on Linux.

Overall this is a nightmare because the Unicode standard apparently has tons of edge cases for dealing with rendering characters in terminals. For context:

http://denisbider.blogspot.com/2015/09/when-monospace-fonts-arent-unicode.html

**Comment by jtdaugherty** [comment]
Repeating here and on #113: @dmwit mentioned this useful mapping of emoji names to Unicode characters: https://github.com/muan/emojilib/blob/master/emojis.json

**Comment by jtdaugherty** [comment]
I'm closing this for now because there is not a clear path forward. Let's re-open this or create a new ticket if this becomes feasible.

**Comment by ntc2** [comment]
Recent discussion indicates that the lack of this feature is detracting from the user experience in the Galois Party Time channel.

**Comment by ntc2** [comment]
Apparently the `sclack` command line client for Slack has this feature: https://github.com/haskellcamargo/sclack/blob/master/resources/example_4.png :D

**Comment by Kabouik** [comment]
This issue was opened 5 years ago but I think image rendering in terminal has gone a long way since then. Sixel support is now much more common, and we have efficient tools like `ueberzug`, `w3mimgdisplay` and kitty's `icat`. Terminal file managers also often have a feature to preview images in terminal now, and as a user of such a file manager, I find it very convenient.

Of course there are also tools to convert images for terminals that don't support real images, like `viu`, `libcaca` or another tool whose name I forgot that converts images into ASCII, but this would probably be hard to read for emojis. I think, however, that those other tools mentioned at the beginning of my post kinda change the relevance of such a feature for `matterhorn`.

The reason I like `matterhorn` is also because I prefer terminal applications for their minimal visuals, overall consistency with any other CLI tool, theming capacity, keybindings, and relative tolerance to a wide range of window sizes and aspect ratios. However, I think it could be nice to have a keybinding that would toggle on and off images (namely emojis and custom emojis) to actually have a feedback of what someone meant with an emoji when the code is not obvious, which can be pretty common on servers with many custom emojis. With a simple keybinding, it would be very easy to just peek at a smiley and then hide it again to restore the minimal visuals of `matterhorn`, with no compromises.

Terminals are also capable of smooth font resizing on the go, which `matterhorn` could detect and constrain images to the line height currently in use.

**Comment by jtdaugherty** [comment]
@Kabouik Thanks for your recommendations.

One thing I need to point out is that this ticket was not about supporting images in Matterhorn; it was about rendering emoji. In practice, almost 100% of emoji are Unicode characters, not images. I linked to some pages above that go into some detail about the state of Unicode (in particular emojis) in terminals, and why those problems make support for emojis in Matterhorn impossible right now. I'm happy to point you at other places where I've written down more of the details about that problem if you like.

As far as the usefulness of rendering emojis is concerned, I agree - it would be nicer to see the graphical version of emoji in Matterhorn rather than needing to figure out what the text version means.

On the topic of images, specifically, a couple things come to mind: first, from a technical standpoint, Matterhorn depends on two other libraries that first need to be modified to support images in any terminal format: `brick` and `vty`. I maintain both of those. If anyone is interested in investigating what that would take and possibly contributing patches, I'd be happy to work with them. Second, from a personal standpoint, I think including images in Matterhorn (in general) basically defeats the purpose of using the application in the terminal. I personally have no desire to see images supported in any way, so I'm not feeling motivated to spend time on implementing the feature myself. But if someone else were to do that and *if* it could be integrated into Matterhorn in a reasonable way, I would willing to add the feature, provided it was off by default.

> Terminals are also capable of smooth font resizing on the go, which matterhorn could detect and constrain images to the line height currently in use.

I have no idea how this would be possible. Terminal emulators do indeed do font resizing, but as far as I know, that detail is not relevant (or available) to how terminal applications send output to terminals to be rendered. So I'm confused about this statement.

**Comment by Kabouik** [comment]
> One thing I need to point out is that this ticket was not about supporting images in Matterhorn; it was about rendering emoji. In practice, almost 100% of emoji are Unicode characters, not images.

I agree but I the discussion above, both emojis and custom emojis are mentioned, and I believe custom emojis are all images. I was indeed referring to custom emojis more than vanilla one in unicode.

I totally understand your lack of motivation for a feature you wouldn't want to use and that you think might defeat the point of `matterhorn`. I agree that images in TUI apps can be a tricky question and not everyone would want them, but a toggle option (that I would probably only use temporarily, it could even just be a "show images while <key> is pressed" as far as I'm concerned) would make everyone happy or, at worse, indifferent… Except it might be a tremendous amount of work, indeed. Unfortunately my coding skills are quite limited as I can only read R and (some) basic Bash, which won't be of any use here.

> I have no idea how this would be possible. Terminal emulators do indeed do font resizing, but as far as I know, that detail is not relevant (or available) to how terminal applications send output to terminals to be rendered. So I'm confused about this statement.

It may very well be a wrong assumption from me, sorry if that's incorrect! I naively thought it would be something that applications could be aware of. I guess for unicode(base emojis), that wouldn't be necessary anyway because the terminal itself would resize those characters like the others, but for image rendering with `ueberzug`, `w3mimgdisplay` or `icat`, that could be a bigger problem since I expect those have to know in advance how many pixels the preview should use, and ideally this should be dependent on the font size/line height currently in use.
