### ISSUE TITLE
Underline should be smarter

### ISSUE THREAD

**Issue by TomMD** [matterhorn-chat/matterhorn#126]
In matterhorn today we can:

```
_underline something_
_orOneWord_
```

But we can't:

```
_Underline_a_c_sytle_variable_
```

I believe it isn't unreasonable to underline till the next sequence of `[NONSPACE]_[SPACE OR EOF OR PUNCTUATION]` and if such a sequence does not exist then fall back to current behavior.

**Comment by jtdaugherty** [comment]
@TomMD it's possible to get what you want by escaping the intermediate `_` characters, but I know you're asking for that to be unnecessary.

I wonder what @jgm thinks about this. Since Markdown doesn't officially define a syntax for underlining, presumably Cheapskate gets to make up its own rule about how to handle this case. I can see the behavior @TomMD proposed being undesirable in the case where you *want* the underlines to apply (in this case) to `Underline`, `c`, and `variable`. If you wanted that but we adopted the behavior proposed here, I don't think you could get any other behavior.

**Comment by jtdaugherty** [comment]
Revisiting this: at some point we talked about using an alternative Markdown parser as a remedy for this. A test of `cmark` (http://hackage.haskell.org/package/cmark) shows that it handles this case as requested here:
```
Prelude CMark Data.Text> commonmarkToHtml [] (pack "_a_b_")
"<p><em>a_b</em></p>\n"
```
(Although I have not investigated what it would take to change from our `cheapskate`-based use of Markdown to `cmark`.)

**Comment by jtdaugherty** [comment]
This is dormant so I've moved it to https://github.com/matterhorn-chat/matterhorn/wiki/Improved-Markdown-Handling
