### ISSUE TITLE
Support adding attachments to messages

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#129]
Right now we support opening attachments but we don't yet support creating messages with attachments.

**Comment by dagit** [comment]
Here is an approach we could take:

  * Require the user to configure a platform specific paste-buffer interaction command (eg., [`pngpaste`](https://github.com/jcsalterego/pngpaste) on macOS).
  * have matterhorn run the command and read the data from the program's stdout

With `pngpaste` you can pass `-` as the filename to use stdout, like this example:
```
$ pngpaste - | wc -l
     363
```

Homebrew users can install `pngpaste` with just: `brew install pngpaste`

`xclip` has similar support on linux: http://unix.stackexchange.com/questions/145131/copy-image-from-clipboard-to-file

CC @jtdaugherty @aisamanra @acfoltzer

**Comment by dagit** [comment]
I started implementing this but I think I need to put it away for now. Here are my raw notes from using the chrome developers tools to spy on the interaction when uploading an image from the web client:

  1. upload
  1. get
  1. create
  1. get_file_infos
  1. get_thumbnail
  1. blob request


# upload
The upload looks like this (I did this on a throwaway instance of MM, so I'm including my auth token).

Request headers:
```
POST /api/v3/teams/ek6no9zqki8stg5xn4ncay5qdw/files/upload HTTP/1.1
Host: localhost:8065
Connection: keep-alive
Content-Length: 97055
Accept: application/json
Origin: http://localhost:8065
X-Requested-With: XMLHttpRequest
Accept-Language: en
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryGbpozn8GpXobshlf
Accept-Encoding: gzip, deflate
Cookie: MMAUTHTOKEN=t3yq6fcqf3g4xynmwscagbtbny
```

Request Payload:
```
------WebKitFormBoundaryGbpozn8GpXobshlf
Content-Disposition: form-data; name="files"; filename="Image Pasted at 2016-11-15 18-04.png"
Content-Type: image/png


------WebKitFormBoundaryGbpozn8GpXobshlf
Content-Disposition: form-data; name="channel_id"

rt86tsbyjpfy8dbwn1j3ur3bpe
------WebKitFormBoundaryGbpozn8GpXobshlf
Content-Disposition: form-data; name="client_ids"

3e952e6b-9266-44a5-b21a-624513b0fef8
------WebKitFormBoundaryGbpozn8GpXobshlf--
```

I don't see the PNG data, but that might be a chrome presentation issue?

The response gives the file's id:
```json
{
  "file_infos": [{"id":"1mkdh4umyid6xctr4cosu4z4xh",
                  "user_id":"53m7xp55air55ps5yeexyqty8e",
                  "create_at":1479261841499,
                  "update_at":1479261841499,
                  "delete_at":0,
                  "name":"Image Pasted at 2016-11-15 18-04.png",
                  "extension":"png",
                  "size":96589,
                  "mime_type":"image/png",
                  "width":538,
                  "height":381,
                  "has_preview_image":true} ],
  "client_ids":["3e952e6b-9266-44a5-b21a-624513b0fef8"]
}
```

I'm not sure what the `client_ids` field contains. We might need to read the MM source to figure that out. I don't know if we already use something for mime-type support, but I think it would be useful here.

# get

As far as I can tell, we can skip this step in matterhorn. It's just using the fileid from the response above to pull down the image in a way that the browser can understand the pasted data:

Requested URL: `http://localhost:8065/api/v3/files/1mkdh4umyid6xctr4cosu4z4xh/get`
Request headers:
```
GET /api/v3/files/1mkdh4umyid6xctr4cosu4z4xh/get HTTP/1.1
Host: localhost:8065
Connection: keep-alive
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Accept: image/webp,image/*,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: MMAUTHTOKEN=t3yq6fcqf3g4xynmwscagbtbny
```
Response headers:
```
HTTP/1.1 200 OK
Cache-Control: max-age=2592000, public
Content-Disposition: attachment;filename="Image Pasted at 2016-11-15 18-04.png"
Content-Length: 96589
Content-Security-Policy: Frame-ancestors 'none'
Content-Type: image/png
Expires: 0
X-Frame-Options: DENY
X-Request-Id: djbunus11tnhpbin93jcxxf1co
X-Version-Id: 3.5.0.3.5.0-rc4.4008c44980dd8ded0d9a08c9f3fc5f36
Date: Wed, 16 Nov 2016 02:04:01 GMT
```

# create

Even though the image is now in the system's database, a message that references the image has not been created yet. This step appears to be doing just that:

Requested URL: `http://localhost:8065/api/v3/teams/ek6no9zqki8stg5xn4ncay5qdw/channels/rt86tsbyjpfy8dbwn1j3ur3bpe/posts/create`
Request Headers:
```
POST /api/v3/teams/ek6no9zqki8stg5xn4ncay5qdw/channels/rt86tsbyjpfy8dbwn1j3ur3bpe/posts/create HTTP/1.1
Host: localhost:8065
Connection: keep-alive
Content-Length: 224
Accept: application/json
Origin: http://localhost:8065
X-Requested-With: XMLHttpRequest
Accept-Language: en
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Content-Type: application/json
Accept-Encoding: gzip, deflate
Cookie: MMAUTHTOKEN=t3yq6fcqf3g4xynmwscagbtbny
```
Request payload:
```json
{
  "file_ids":["1mkdh4umyid6xctr4cosu4z4xh"],
  "message":"",
  "channel_id":"rt86tsbyjpfy8dbwn1j3ur3bpe",
  "pending_post_id":"53m7xp55air55ps5yeexyqty8e:1479261842310",
  "user_id":"53m7xp55air55ps5yeexyqty8e",
  "create_at":1479261842310
}
```

# get_file_infos

This step is also optional, it's just refetching the meta data because it received a post that references a file.

# get_thumbnail

This step is also optional. It's just getting the thumbnail to display inline.

# blob request

I don't understand this step, but I'm pretty sure it's optional. It appears to be fetching the image data yet again, but as a jpeg this time. Here is the request URL:
`blob:http://localhost:8065/40f0093d-7f65-46d5-bff8-102180052f7f`

**Comment by tgy** [comment]
@dagit: thank you for your work. I can't wait to see this coming.

**Comment by abhin4v** [comment]
Why does the attachment have to come from the paste-buffer? Why not give the user a file select field (like Emacs find-file command) and upload the selected file using the API endpoint? I think that will be easier to implement and cover most of the use cases.

**Comment by jtdaugherty** [comment]
@abhin4v That was merely a proposed approach, not the only possible one. Supplying the attachment via paste buffer is better than providing a filename in cases when saving the attachment to a file first would be annoying, such as when one comes across an image on the web. In that case it would be nice to just "copy" the image and attach, which is why that behavior was proposed. But providing a file input would also be important for cases where you already have a local file.

**Comment by abhin4v** [comment]
Maybe, it can support both the ways. I am willing to work on the file selection mode for uploading, if it's okay with you.

**Comment by jtdaugherty** [comment]
Yes, that would be great! Once you have had some time to think about it, please post your proposed approach here, along with details about how you imagine the UI will work. Thank you!

**Comment by jtdaugherty** [comment]
Support for file uploads is now complete in the `feature/attachments` branch. This will be merged to `develop` soon.

**Comment by jtdaugherty** [comment]
This feature is now finished as of 08e14edafe5f70c002f37585bdec516dcbe0bb57 in `feature/attachments` and will be merged to `develop` today. This ticket had discussion on another approach for attachments that would still be nice to have, but I'm going to wait until that comes up again to decide whether to invest time in that option. Thanks, everyone!
