### ISSUE TITLE
We should escape backticks in in-line code

### ISSUE THREAD

**Issue by TomMD** [matterhorn-chat/matterhorn#134]
For example:

```
   `take \`{4} xs`
```

Should render as:

```
   take `{4} xs
```

**Comment by aisamanra** [comment]
This is a Markdown-ism, and we want to interpret the Markdown as close as possible to the web UI so that non-Matterhorn users see the same thing as us. I'm strongly against introducing new Markdown constructs that don't also show up in the web UI for that reason, and using `\` as an escape character would do just that.

Luckily, there is already a way of doing this, though; if you want a backtick in inline code, you can begin and end the inline chunk with multiple backticks

~~~
  ``take `{4} xs``
~~~

will get rendered as

~~~
  take `{4} xs
~~~

Will that address your use-case?

**Comment by TomMD** [comment]
@aisamanra Yes, that works.  I didn't realize inline markdown had similar rules to fencing.
