### ISSUE TITLE
`/sh` commands that print to `stderr` borks the terminal

### ISSUE THREAD

**Issue by TomMD** [matterhorn-chat/matterhorn#147]
For example, `/sh ghc hPutStrLn stderr "hi"` breaks things pretty badly.

**Comment by aisamanra** [comment]
As of c8c44ab this specific problem will no longer come up, because we capture `stderr` appropriately. Right now, we only report what actually _happened_ on `stderr` if the command fails; otherwise, we silently discard it. If you want your script to include `stderr` in its output, you should redirect it in the script itself.
