### ISSUE TITLE
Clear informative messages from conversation channels on channel switch

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#149]
@tommd reported a concern about how we currently show informative (error and client) messages in conversation channels. The issue is that these can clutter up the display of messages because they persist for the lifetime of the client session. To address this we came up with an alternative user experience that should preserve these important messages and their utility without the misbehavior that Tom mentioned:

* Create a special client messages channel where all client messages and errors get posted
* Make it possible to use `/focus` with this channel and give it a special name like `##system` to avoid namespace clashes with server channels
* *Also* post client messages to the current conversation channel as usual, BUT when we change channels, cull those messages from the message list (similar to how `New Messages` bars are handled).

My hunch is that it would be best if this special message channel did not appear in the channel list, and that it wouldn't make sense to give this channel unread message notification capability. It'd be there for the user to consult if, for example, a channel change lost a potentially important informative message.

**Comment by aisamanra** [comment]
Per out-of-band discussion, we think this is still not a bad idea, but we're unlikely to get around to it any time soon, both because the change proposed would at this point be a larger breaking change, and because the problem it's meant to address hasn't been a major sticking point in practice. We'd be happy to reopen this in the future, but for now we're closing it.
