### ISSUE TITLE
copying verbatim sections to clipboard

### ISSUE THREAD

**Issue by dagit** [matterhorn-chat/matterhorn#152]
Right now if someone shares a snippet of text with me, I need to use the web client to get into my clipboard. Maybe we need a command similar to `C-o` that puts the code block into the clipboard.

**Comment by aisamanra** [comment]
I was thinking about this issue recently, and I was wondering whether it would be best to implement this as a command over messages not unlike 'reply', 'delete' or 'edit', once those are in place. My rationale here is this:

· We're going to need to support the features above, and in order to support them, we'll need to have a mode where you scroll up or down, selecting messages as you go, with the ability to reply or (if they're your own messages) delete and edit implemented as commands on that. My completely off-the-cuff suggestion is using `M-m` for entering this mode followed up `up`/`down` to select, and then single-letter commands like `r` for reply, `d` (with confirmation) for delete, and `e` for edit.
· Given that this already needs to exist, we could easily add another command: `c` for copy. This could give you a menu of "interesting things" to copy, including URLs, verbatim snippets, and the whole message.
· The alternative would be a new `C-o`-style mode, but that's yet another key combo taken for this feature, and I can imagine wanting to copy a lot more than just verbatim blocks (like quote blocks, URLs, or even whole messages, especially if I want to, say, select a non-verbatim phrase someone mentioned to paste it into a browser), which means this view could get a lot more cluttered than URL view. You would have less of a problem here if you could first select the relevant message, and then select the thing to copy, and it'd be more flexible in the long term.

**Comment by jtdaugherty** [comment]
I'm in favor of the `M-m` / scroll / `[rdec]` workflow suggested and that matches what I'd been imagining, too.

**Comment by dagit** [comment]
This came up again today.

**Comment by aisamanra** [comment]
I mocked up a version of this in the feature/message-selection branch, but sadly had to revert it: the `Clipboard` package I was using to put stuff into the clipboard only supports X11 and Windows. Still: once we have the ability to put stuff on the clipboard on OS X, it should be pretty straightforward.

**Comment by aisamanra** [comment]
There's a working version of this using `Hclip` now. It's not as flexible as it could be—it will only copy verbatim blocks, and only the first verbatim block in a message—but it exists: go into message-selection mode, select a message that contains a verbatim block, and press `y` to `y`ank it to the clipboard.

@dagit, I'm not gonna close this because I want you to try it and see if it suffices for your use-cases, or if you'd like more features (like being able to select more things and choose what's selected) before we consider this closed.

**Comment by jtdaugherty** [comment]
@dagit can you take a look at this soon and either sign off or comment on what else needs to be done?

**Comment by dagit** [comment]
I just tried it on a message with mixed content and I think it would be better to copy the entire message and support yank on all messages. Either that or give me a UI to visually select what I want.

**Comment by jtdaugherty** [comment]
I'm closing this since the bulk of this request is done; more details on further work can be found on #171.
