### ISSUE TITLE
Support opening help content in $PAGER

### ISSUE THREAD

**Issue by amaloz** [matterhorn-chat/matterhorn#185]
It'd be nice to be able to search within the help menu, as I often forget the key bindings and searching for, e.g., "URL", would speed up finding the right bindings.

**Comment by jtdaugherty** [comment]
@amaloz while supporting search in the Help interface in the general case would be quite a lot of work, we could support this specific request by doing something like spitting out the current keybindings into, say, `$PAGER`, so you can browse them that way. Would that be sufficient?

**Comment by amaloz** [comment]
Yep, that should be fine.

**Comment by jtdaugherty** [comment]
At this point I don't think it's practical for us to implement this behavior. Right now there is too much Haskell logic that is involved in formatting the help text when it is presented in the interactive application. Generalizing that or making Markdown responsible for the formatting in order to make this work would be a ton of effort. Going back to the original request, @amaloz - you can now see generated keybinding and command lists with `matterhorn` on the command line, i.e.,
```
$ matterhorn --help
matterhorn
  ...
  -k       --keybindings-text      Print keybindings effective for the current configuration in plain text format
  -K       --keybindings-markdown  Print keybindings effective for the current configuration in Markdown format
  -m       --commands-text         Print available commands in plain text format
  -M       --commands-markdown     Print available commands in Markdown format
```
Do those features help you get what you originally wanted here?

**Comment by amaloz** [comment]
Sure that should work. Thanks!

**Comment by jtdaugherty** [comment]
Okay. Thanks!
