### ISSUE TITLE
Understand cabal new-build warning about QuickCheck

### ISSUE THREAD

**Issue by dagit** [matterhorn-chat/matterhorn#231]
I build matterhorn this morning and got this (potentially) interesting message from cabal:

```
Configuring library for QuickCheck-2.9.2..
Warning: The package has an extraneous version range for a dependency on an
internal library: QuickCheck ==2.9.2, QuickCheck ==2.9.2, QuickCheck ==2.9.2,
QuickCheck ==2.9.2. This version range includes the current package but isn't
needed as the current package's library will always be used.
Preprocessing library for QuickCheck-2.9.2..
```

I don't think I understand the warning so this ticket is a reminder to find out what it means so that we can decide if we care or need to take further action.

**Comment by jtdaugherty** [comment]
Looking at the `cabal` file for QuickCheck `2.9.2`, this is because QuickCheck specifies the version of its self-dependency explicitly whenever it is specified at all:
```
Test-Suite test-quickcheck
    ...
    build-depends:
      ...
      QuickCheck == 2.9.2,
```
But specifying the version `2.9.2` is unnecessary because just specifying `QuickCheck` without a version implies use of the library in the package (thus "the current package's library will always be used."). So there's nothing for us to do since this is a harmless package linting issue for the QuickCheck maintainer.
