### ISSUE TITLE
Unify command execution code paths

### ISSUE THREAD

**Issue by dagit** [matterhorn-chat/matterhorn#232]
Right we have at least two ways to run external commands:
   * some are run asynchronously and the result is stuffed in a queue to be logged (for instance, opening an attachment)
  * some are run synchronously (like the shell script command `/sh`)

Currently these two code paths can evolve separately and this is undesirable in terms of maintenance. In fact, this recently came up because one path not checking exit codes while the other path did. See 37b2aa7391dab234fd0b7f5db94979d1dc9a9126.

**Comment by jtdaugherty** [comment]
Right now the async status is flipped from the original ticket message:
* Commands run through `/sh` are run asynchronously.
* Commands run through URL-opening are run synchronously.

We have two reasons to run commands:
* For side effects only, e.g. URL opening etc. In this case *any* output is deemed inappropriate and is logged, and exit failures are noteworthy. When errors are encountered, we want to mention the log file in the current channel.
* For output, e.g. `/sh`. In this case stdout is required and stderr is inappropriate and is reported to the user in the current channel. Exit failures are also noteworthy.

The two strategies are different enough that I don't think there's enough common logic to unify them *completely* since doing so would require threading through behavioral parameters that would not improve the situation, but the things I think would be helpful are:

* Run URL-opening commands asynchronously
* Log `/sh`-driven script output to the log file instead of reporting it to the channel

**Comment by jtdaugherty** [comment]
The first part is now done as of 71e11d2edbcb09acc96acb2948be313a508f860c.

**Comment by jtdaugherty** [comment]
It turns out that `runLoggedCommand` can be generalized a bit to take care of the `process` work by just returning the `ProgramOutput` it sent to the subprocess logger. That, combined with an extra optional stdin input parameter, makes that function usable for both cases, so I'm doing that, too.
