### ISSUE TITLE
hostname cannot begin with `https://`

### ISSUE THREAD

**Issue by dagit** [matterhorn-chat/matterhorn#242]
We assume the hostname is something that will resolve in a DNS query but users do not necessarily know this and may try `https://myserver` and get odd failure modes from matterhorn.

There are several ways to approach this including:

  * Check for `http(s)://` and strip it out
  * Check and warn
  * Show the user more explicitly in the dialog what URL/port is being constructed from the values they have provided

**Comment by jtdaugherty** [comment]
I'm open to either:
* *Disallowing* a scheme entirely (since it's implicitly `https` anyway)
* *Requiring* a scheme *and* port as part of a single URI input field rather than having port and hostname separated
My concern is that anything else will cause poor interactions between a smart hostname input that knows about schemes and the port input.

**Comment by kquick** [comment]
What is the natural input for mattermost-api?  A URL or explicit fields?

**Comment by jtdaugherty** [comment]
Hostname and port separately.

**Comment by kquick** [comment]
Then I would suggest that matterhorn stick to that methodology, and add some validation to the fields (e.g. only valid characters for hostname, only numbers for port, etc.) with errors displayed underneath the associated field when invalid characters are detected.

**Comment by jtdaugherty** [comment]
That sounds good to me (so invalid chars for hostname would be at a minimum `:` and `/`).

**Comment by jtdaugherty** [comment]
CC @RyanGlScott
