### ISSUE TITLE
Add support for desktop notifications via libnotify

### ISSUE THREAD

**Issue by asciijungle** [matterhorn-chat/matterhorn#249]
It would be great if matterhorn would notify when i get mentioned by sending desktop notifications via libnotify. Of course this should be configurable (on/off; only mentions/general activity).

There exists a package with bindings for libnotify on hackage: https://hackage.haskell.org/package/libnotify-0.2/docs/Libnotify.html

**Comment by jtdaugherty** [comment]
@asciijungle - thanks for the ticket. @aisamanra is going to look into some approaches for this.

**Comment by aisamanra** [comment]
We'd like to do this in a way that's cross-platform (so it can also support e.g. [growl](http://growl.info/) on OS X), which means it's going to be slightly more complicated than just using the `libnotify` package. I'm speculating that it might be worth trying to do this in the most generic way possible: by shelling out to another tool, which would let you use `notify-send` on Linux and `growlnotify` on OS X, or even write your own script that lets you do something like search for certain pieces of text in the body of the message before choosing to display it.

My one worry here is that invoking a shell for every message might be a bit slow, but I don't know if messages are common enough that that would make a difference, so I might just implement that variant and see whether that's a concern that comes up in practice.

**Comment by jtdaugherty** [comment]
@aisamanra I'd imagine that whatever gets invoked for this would run quickly enough, and we could also compensate for that by using a separate work queue.

**Comment by jtdaugherty** [comment]
For posterity: another reason we'd like to avoid `libnotify` is due to the shared library dependency. Although `libnotify` is available on many platforms, it is not *installed* by default on the platforms we support, and shipping a binary that depends on the presence of a shared library that the user has to install is undesirable. The approach that @aisamanra suggested entirely avoids this.

**Comment by glguy** [comment]
For supporting additional functionality provided by external C libraries, I've been using dynamic loading (dlopen) to pull in libraries like libnotify and in another case libotr. Even if matterhorn doesn't get a full extension API, this could be an option providing native support for these interfaces while not /requiring/ users have libnotify available to use the pre-built executables.

**Comment by jtdaugherty** [comment]
Good to know!

**Comment by tgy** [comment]
Using `dlopen` to dynamically load `libnotify` sounds like a very decent way to go. I'd love to see this notification feature coming.

**Comment by jtdaugherty** [comment]
@tgy right now we're targeting the completion of this feature in our Phase 2 2017 milestone. For clarity: we aren't going to use the `dlopen` approach here, but at any rate that's good to know about for the future.

**Comment by cheapRoc** [comment]
Any feedback on when this feature landed or might land in the future? Sounds like the only remaining Matterhorn feature that I use routinely across other MM clients so I'm pretty stoked.

**Comment by jtdaugherty** [comment]
We aren't sure when we'll be able to get to this right now. I had tentatively planned to take a closer look at it in the next few months, but other issues have required the team's attention. We are definitely still interested in having this done, and if someone wanted to contribute changes to this effect, we'd be happy to work with them!

**Comment by jasom** [comment]
I was thinking of adding code to run a configurable system command during postProcessMessageAdd.  Would that be a sane way of implementing this?  Right now I can get minimal notification by running in a urxvt with a special bell handler, but I'd like something a bit better.

**Comment by jtdaugherty** [comment]
> I was thinking of adding code to run a configurable system command during postProcessMessageAdd. 

Can you say a bit more about what behavior/feature this is intended to support?

**Comment by jtdaugherty** [comment]
(Which is to say, it could be used to support notifications, but I wanted to be sure I knew how you were thinking about it)

**Comment by jasom** [comment]
Yes, this is to support notifications with regards to issue #249

**Comment by jasom** [comment]
Notifications is my biggest missing feature from matterhorn right now, and I see you have other priorities, so I'm offering to implement it in the manner I describe (basically replacing the maybeRingBell that is used right now).

**Comment by jtdaugherty** [comment]
`postProcessMessageAdd` is probably a fine place to start. Yeah, the calls to `maybeRingBell` could be replaced with some new function like `notifyUser` that calls `maybeRingBell` and does whatever else is appropriate.

A couple of other thoughts, if you're going to tackle this:
 * Right now the `PostProcessMessageAdd` type carries no information about which channel was involved, but if we're going to use it to do richer notifications, it needs to be augmented with e.g. a `ChannelId` so the notification can include the name of the channel that got new messages.
 * Use `runLoggedCommand` to run the command in question.
 * Add a config setting, say `notification-command`, that is optional.
 * The message command interface needs to be well-documented, and we need to enumerate the kinds of situations in which it will be invoked. For now that might just be on new posts, but then we need to decide on how its interface will work. For scripts, we pass input on `stdin`. For this I'd recommend `stdin` input with the first line being the notification type, the second being the channel name, the third being the number of new messages, say. As you look into this, let us know if this will work or needs adjustment.

Also, in the longer term we probably will move to a `dlopen()` approach (even though above I said we wouldn't), but for now let's just go with this approach because it's much more expedient. We need to do more thinking on how a `dlopen()` approach needs to work.

**Comment by jtdaugherty** [comment]
Also: we can discuss this in real time if you stop by the `matterhorn` channel on `pre-release.mattermost.com`.

**Comment by jtdaugherty** [comment]
Another thing I wanted to clarify in case it wasn't clear above: bell-ringing and external commands should both be valid options for notifications *to be used simultaneously*. That is, they are not mutually exclusive and the new command support should not replace or otherwise remove bell support. Many users will not want to use this feature once it's implemented and would still prefer to ring the (usually visual) bell.

**Comment by jtdaugherty** [comment]
@jasom's patch (PR #387) has been merged to `develop`. This gets us notification support via an external, configurable command. Since that takes care of the main request in this issue, I'm going to close this.

For posterity: we have some other ideas about some things related to the `dlopen` approach suggested above, but we won't have time to get to that soon. The next step on that is for us to do some thinking/scoping and write up some design content on the wiki, after which point it might be fleshed out enough for us or a contributor to work on it.
