### ISSUE TITLE
Support for multiple teams in one session

### ISSUE THREAD

**Issue by bernerha** [matterhorn-chat/matterhorn#260]
It would be nice to manage teams in one window rather than start a new process.
Or is there already an option?

**Comment by jtdaugherty** [comment]
@bernerha - there is not yet support for this. Thanks for the ticket!

**Comment by bernerha** [comment]
Another behaviour to mention is (the behaviour is fine, it depends on this improvement) that I got the private message on every process/session with different teams.

**Comment by jtdaugherty** [comment]
Yeah, while there isn't much we can do about that now, that would go away once a single session can handle multiple teams.

**Comment by jtdaugherty** [comment]
I'm going to close this because it's marked high-level, will involve a major overhaul of many aspects of the client, and is not on our road map any time soon. I think as we do other work improving the client, this idea becomes more feasible, but I don't think we will start on it any time soon since we have a lot of other work to do.
