### ISSUE TITLE
Improve username color distribution

### ISSUE THREAD

**Issue by dagit** [matterhorn-chat/matterhorn#32]
With only 16 colors we're going to have collisions. So this may not be fixable. This ticket is here to serve as a place to document ideas related to improving the coloring.

I'll go first, here is a vague rule I think would help:
- Use different colors for different length nicks, especially when the nicks have similarity (eg., `batman` and `badman` should preferably be different colors). We might compute similarity using hamming distance or levenshtein distance.

If you can think of other heuristics then let's try to collect them here.

**Comment by jtdaugherty** [comment]
Right now we use `Hashable`'s `hash` function to index into the color list. If we can come up with other deterministic choice functions then that will work well.

**Comment by jtdaugherty** [comment]
One idea I had that would basically just reduce the chances of collision would be to detect when the terminal supports 256 colors and use a larger palette.

**Comment by jtdaugherty** [comment]
I'm closing this, primarily because we haven't gotten any support requests to fix this, but also because aside from using 256 color support, I'm not sure there's much we can do about this. (I'm also not confident that the proposed heuristics will improve the distribution in a way that would be obviously different from how it is now.)

If anyone has ideas on how to make this better, let's start with a candidate patch and go from there.

**Comment by dpb1** [comment]
As you were looking for feedback, I'd love 256 color support!  I run `TERM='screen-256color'` for my IRC clients for just this reason.  The UI is fine, but for names, it's nice to have a wider distribution, as you hit 8 in a channel talking way too easily.  I realize that adding a "me too" on the end of this isn't super helpful, but this is exactly the solution in other clients I've used when this problem is hit.

**Comment by jtdaugherty** [comment]
I've started working on 256-color support on a branch:

https://github.com/matterhorn-chat/matterhorn/tree/feature/username-colors-256

**Comment by jtdaugherty** [comment]
From a discussion with @kquick, one of the things we need to do on this branch now is to prune colors that are too dark for the dark built-in theme and too light for the light built-in theme.

**Comment by jtdaugherty** [comment]
As of 6f3b8e3974090cb4b14f6b2de2608ce62bb19f89, this has now been resolved on `develop`. The primary changes are:
* New built-in color themes, `builtin:dark256` and `builtin:light256`, which offer 256-color username colors but are otherwise identical to the light and dark built-in themes, and
* A command `/username-attribute` that can be used to determine which attribute name Matterhorn uses to render a given username, in case users want to override that color choice.
