### ISSUE TITLE
Support reactions to messages

### ISSUE THREAD

**Issue by abhin4v** [matterhorn-chat/matterhorn#330]
The mattermost web UI lets users react to messages with emojis. As of now, matterhorn shows the emoji reactions to messages but does not let the user post new reactions or delete user's reactions on the messages. It'll be nice to have this ability.

 Mattermost API has endpoints for posting reactions (`POST /api/v4/reactions`) and deleting them (`DELETE /api/v4/users/<user_id>/posts/<post-id>/reactions/<emoji-name>`). The list of the in-built emoji names can be obtained from <https://github.com/mattermost/mattermost-webapp/blob/master/utils/emoji.jsx>. The list of the custom emoji names can be obtained from the API endpoint `GET /api/v4/emoji`. The emoji names are needed to provide auto completion while the user types the reaction.

**Comment by jtdaugherty** [comment]
Thanks!

Is the "jsx" file the only way to get the built-in emoji name list? I'm not a fan of the possibility of having to parse the "jsx" file linked above so I'm wondering if there are other options.

Also, to be clear, Matterhorn cannot support actually showing the Unicode emoji characters (for reasons I'm happy to provide). So this feature can only go so far as to deal with reactions in terms of names, just as Matterhorn currently only shows the reaction names on posts that have them.

If you plan on working on this, let's use this ticket to hash out further details (e.g. UI/UX and technical issues). After that I'll want this to be split up into tickets for specific tasks (e.g. fetch/parse emoji list, support adding new reactions, support removing existing ones).

**Comment by abhin4v** [comment]
I looked into the code which generates the JSX file (https://github.com/mattermost/mattermost-webapp/blob/master/build/emoji/make-emojis). It seems to be taking the list of emojis from the ruby gem gemoji, filtering out some of them, and then dumping them into the JSX file. So the original source of the emoji names is from a file in the gemoji gem repo: https://github.com/github/gemoji/blob/master/db/emoji.json. We can also use the same file and run the same filters to come up with the list of emoji name.

I am aware that Matterhorn only shows reaction names and I am fine with that.

I do plan to work on this. My rough idea is as follows:

1. During the build, download the aforementioned JSON file.
2. Use template haskell to parse the JSON file and embed the emoji names in a module in the matterhorn code as a list.
3. At startup, this list of emoji names is used to create a trie which is kept as a field the `ChatResources` instance. This trie will be used to autocomplete the emoji names when reacting to the messages.
4. In the message select mode, a new option is show to react to the message (I am thinking of using `t` as the keybinding). When this option is chosen, the editor switches to a new mode which allows typing the reaction emoji with autocompletion support.
5. On pressing enter, the emoji is posted as a reaction to the message using the mattermost API endpoint I mentioned before.
6. The deletion of reactions is a little tricky because the user may have reacted to a message with multiple emojis and right now we do not show which reaction is from which user. Maybe once this issue  https://github.com/matterhorn-chat/matterhorn/issues/301 is fixed, we can use the message details popup to allow the user to choose the emojis posted by them for deletion. We can them delete the reaction by calling the relevant mattermost API endpoint.

Let me know how this sounds to you and I can get started. I can create separate issues for these steps if you wish so.

**Comment by jtdaugherty** [comment]
Assuming the above gets done, items 1 and 2 become something like

1. At startup, fetch the emoji list from the server.

(Then build the trie from that.)

Otherwise, though, the above plan looks good to me. I'd very much appreciate a batch of tickets to that effect, with this ticket linking to those. If you want, you can start working on this assuming a stubbed API endpoint and get the rest of it going. Meanwhile either of us can lobby the server development team - let me know which you prefer.

**Comment by jtdaugherty** [comment]
It turns out the thing I want has already been requested:

https://mattermost.atlassian.net/browse/RN-301

**Comment by jtdaugherty** [comment]
I left a comment on their ticket.

**Comment by jtdaugherty** [comment]
I got into a conversation with Harrison Healey, the author of that ticket and also a Mattermost developer, about this issue. He's saying that it'll be a while before they sort out this API addition because it's connected to other, larger performance problems with custom emoji. As a result we can't expect this to arrive soon. However, he did offer a compromise, which is to emit a separate JSON file containing the emoji information. He's putting a pull request together as I write this and estimates that it'll be available in Mattermost 4.5. As a result I'd like the revised steps to be:

* Download the JSON emoji list from the minimum supported Mattermost release (4.5 once it is released). Check it into revision control in the Matterhorn repository.
* At release time, if the Matterhorn version is changing to indicate a change in supported server version, repeat the previous step and update the checked-in file. To support this, write a shell script that, given a Mattermost version, will clone the relevant Mattermost repository and tag to obtain the right version of the emoji list.

1. Use template haskell to parse the JSON file and embed the emoji names in a module in the matterhorn code as a list. (For anyone else reading: we'll use TH over reading a file here to avoid issues with identifying the right path to the emoji list file in user environments.)
2. At startup, this list of emoji names is used to create a trie which is kept as a field the ChatResources instance. This trie will be used to autocomplete the emoji names when reacting to the messages.

**Comment by jtdaugherty** [comment]
Here's the relevant PR: https://github.com/mattermost/mattermost-webapp/pull/377

**Comment by abhin4v** [comment]
Thanks for sorting this out @jtdaugherty. I'll pick this up after Mattermost 4.5 release and implement it as you suggested.

**Comment by jtdaugherty** [comment]
Thanks, @abhin4v!

**Comment by jtdaugherty** [comment]
From the 4.7 changelog:
```
Added POST /emoji/search, GET /emojis/name/{emoji_name}, and GET /emoji/autocomplete
to add consistency with user search/autocomplete endpoints. These API endpoints ensure
that the benefits of GET for important performance related actions such as autocompleting
are included.
```
I haven't investigated but those new endpoints might be useful when working on this ticket.

**Comment by jtdaugherty** [comment]
CC @spaceships

**Comment by jtdaugherty** [comment]
@spaceships is going to be taking a look at dealing with the emoji data from Mattermost, along with a design for a UI to add reactions to messages.

**Comment by jtdaugherty** [comment]
@hmhealey I took a look at the patch for `emoji.json` and now I'm wondering how we can get access to that. I don't see an API method to fetch it via HTTP. What do you have in mind?

**Comment by hmhealey** [comment]
It's just compiled into the web and mobile apps right now, so it's not accessible through the API. I've thought a bit in the past about handling those system emojis the same as custom emojis so that they're accessible through the same APIs, but no work has been done in that direction.

Would compiling the json file into Matterhorn be an option for the time being? `emoji.json` hasn't changed in over a year now, and there's some issues we're trying to work out before making further changes to it.

Alternatively, we could probably just add `emoji.json` to the statics folder so that Matterhorn could access it through the API, although that would mean that this feature only works with newer versions of Mattermost, and we'd have to make a note to also update that version of the file when we make further changes

**Comment by jtdaugherty** [comment]
I think it would be okay for us to just bundle it with Matterhorn and periodically update it. That's what we do with the XML files that drive our syntax highlighter. Thanks for the update!

**Comment by jtdaugherty** [comment]
As of 3d99bf614a6852089afa5e41edc408d5f458f96d, Matterhorn now supports adding and removing emoji reactions to posts as well as tab-completion of emoji in the editor (both local and server-side custom emoji). This will go out in the next release. Thanks, everyone!
