### ISSUE TITLE
better handling of search results

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#359]
Current behavior:  "/search<RET>" will pop-up the search results box, whose contents are `Searching ...` and never get updated.  Eventually, hitting ESC will dismiss the search box (although there are no instructions for doing that) and an error will be displayed in the current message window: `MattermostError: {mattermostErrorId = "api.context.invalid_body_param.app_error", mattermostErrorMessage = "Invalid or missing terms in request body", mattermostErrorStatusCode = 400, ...}`

There are a couple of observations here:
1. Most of our commands are safe to enter without parameters (e.g. /join), so /search should try to follow the same model.
2. An empty search should probably just show a message that there were no search terms.
3. Any errors returned from a search command should be displayed immediately in the search box (or elsewhere, see https://github.com/matterhorn-chat/matterhorn/wiki/Error-Handling).

**Comment by jtdaugherty** [comment]
The patch I pushed takes care of (1) and (2), and effectively eliminates (3) because that was only occurring because we permitted empty search strings to get through to the API call. It's still possible for lower-level errors to be triggered by search API requests, such as connection exceptions, but I don't think putting those in the search UI does anything to help the user deal with them so I think those fall under the larger umbrella of the wiki page you mentioned. Consequently I think we can call this done.
