### ISSUE TITLE
JSONDecodeException: expected Props, encountered Null

### ISSUE THREAD

**Issue by jclulow** [matterhorn-chat/matterhorn#360]
I believe we updated our Mattermost server recently, and since that time I've started to see errors like this:

```
An unexpected error has occurred! The exception encountered was:
JSONDecodeException {jsonDecodeExceptionMsg = "Error in $.posts.gmopynjguinsmpcoqqd9pj5c5e.props: expected Props, encountered Null", jsonDecodeExceptionJSON =
```

Originally they were crashing the client, but now that I'm running `40600.1.0` they emit a large red body of text which appears to be the body of the response to get more messages.  Indeed, when I sift through and find the post in question, it _does_ have a `null` value for `"props"` instead of the usual empty object (`{}`).

It would be nice if Matterhorn was able to either treat a `null` value for `props` as if it were an empty object, or perhaps treat the entire response as a failed request and retry.  It definitely doesn't happen all the time, because I'm generally able to use the client for quite a while between errors.

**Comment by jtdaugherty** [comment]
What version of the server are you running?

**Comment by jclulow** [comment]
According to "About Mattermost" in the web UI: `4.2.0`.  There are more details, if it helps:

> Build Hash: a5ce36d0882ae1b4b409a7b68233bf89591a5f95
EE Build Hash: 38697f6cf2a9183e410e88acd13191390711d38f
Build Date: Wed Sep 13 22:25:30 UTC 2017

**Comment by jclulow** [comment]
I guess I assumed we had updated the server, because as far as I know none of us have experienced the behaviour until very recently -- but now see it often.

**Comment by jtdaugherty** [comment]
If you're running `4.2.0` on the server, it's important that you run a version of Matterhorn that most closely matches that version. That would be either `40000.1.0` or `40400.0.0`. Newer versions of the client are not guaranteed to be backwards-compatible, since the upstream server development does not make that guarantee. (The official web client, for example, automatically reloads itself if the server underneath it gets upgraded.)

Can you try one of those other versions and see if you get better results? Alternatively, you can upgrade to Mattermost 4.6.

**Comment by jtdaugherty** [comment]
(I'll also note that this issue is definitely worth fixing, and we will! But in general, version parity between the client and the server will be important. That's why we have the versioning scheme that we do: so that users can tell which version of the client they should use to pair with their server.)

**Comment by jtdaugherty** [comment]
As of https://github.com/matterhorn-chat/mattermost-api/commit/afdb537c81213587b14a5bbc8db321549f14134a, this should be fixed.
