### ISSUE TITLE
Question on support for Slack

### ISSUE THREAD

**Issue by prabhu-madanagopal** [matterhorn-chat/matterhorn#364]
Hi,

I am a Haskell learner, I want to build a matterhorn for slack in Haskell. How easy/difficult (amount of work) to adapt matterhorn to support Slack? Or is it better to start from scratch?

Thanks for you help,
Prabhu

**Comment by dagit** [comment]
It would be quite a bit of work to adapt matterhorn to work for slack.

You'd need:
1. API binding for the https/websocket communication
1. Haskell data structures for modeling the slack state locally
1. UI changes to fit slack's interaction model

You'll need (1) and (2) regardless of whether you adapt matterhorn. (3) might be easier if you started from scratch, using the code in matterhorn as a reference.

I'm going to close this ticket as our issue tracker isn't a good place to have such discussions.

Anyway, I encourage you to try making an API binding first. See how that goes.

**Comment by jtdaugherty** [comment]
@prabhu-madanagopal - we have a long-term desire to move to supporting other slack-like protocols in Matterhorn. @dagit mentions some of the moving parts that will be required, but it's going to be a lot of work. I think @dagit's suggestion of starting with API bindings is a good one, since that is necessary either way.

As far as Matterhorn goes, the development team would like to plot a course for getting to support for other backends. Once we have a plan assembled, whoever does that work (either on the development team or a community contributor) will need to be very comfortable with large refactorings and will need to work closely with the development team to do the work. If you are interested in helping out with Matterhorn but are somewhat new to Haskell, I would recommend starting by helping  out on other, smaller tickets first. We'd be happy to give pointers if you wanted to fix bugs, etc!
