### ISSUE TITLE
Channels and users with unread should always be visible

### ISSUE THREAD

**Issue by mgerdts** [matterhorn-chat/matterhorn#376]
I'm subscribed to about 10 channels and my team has many dozens of users.  They don't all fit in the left column.  While I'm chatting with anyone whose username is not near the beginning of the alphabet, all of the channels have scrolled off the top.  There seems to be no easy way to see if there's new activity in the channels I may be chatting in without changing focus to a channel.  In the GUI client this isn't as much of an issue, because it is easy enough to just hide the users that I don't talk with on a regular basis.

One of the following would be nice to have:
- Active channels and active users are sorted to the top of the section
- Add a new section above *Channels* called *Active* that aggregates the channels and users that have unread messages or have recently been used.   Presumably there would be an option to configure how big this is.  For me, in the typical day there are fewer than 20 channels + users that I talk with, so setting it to 20 would mean that I can always see those channels and users that I care most about.

**Comment by jtdaugherty** [comment]
Thanks! We have some changes to the user/channel sidebar planned and we'll take this into account.

**Comment by jtdaugherty** [comment]
I'm going to close this as essentially a duplicate, but I'll make sure the concerns raised here get added to our list of considerations for our work on this. Thanks again!

**Comment by jtdaugherty** [comment]
@mgerdts We've been hard at work on some changes that should help with this. In particular, on our `refactor/user-list` branch which is nearing completion:
* Unread 1-on-1 DM and group channels will float to the top of the Direct Messages section
* Users will only appear in your sidebar if you have talked to them recently or if they have unread messages

That branch is concentrating on bringing Matterhorn closer to how the web client handles the DM section of the sidebar, rather than its previous behavior of always including all of the server's users in the sidebar, which has presented a lot of problems.
