### ISSUE TITLE
tty escapes in user alias fields are processed

### ISSUE THREAD

**Issue by numericillustration** [matterhorn-chat/matterhorn#390]
We've noticed that its possible to resize the window and other nefarious things via tty escape codes in fields like user aliases.

**Comment by kquick** [comment]
Oh fun.  :-)

Thanks for the report!

**Comment by bcantrill** [comment]
I would like to verify that @arekinath is the least popular person in the company -- or certainly among the subset of us who use Matterhorn. But spare your sympathy: he has brought much of this on himself!

**Comment by jtdaugherty** [comment]
@kquick like `ServerTime`, I'd like to explore a use of a `newtype` for sanitized text. We could sanitize all incoming text to that type to pay the penalty only once per value, *and* only pay it in the cases where we know we're going to need to display it. Basically, start in `Types` and change most `Text`s to the `newtype`, then follow the type errors.

Also, it's very nice that most if not all of the text we display is in terms of Matterhorn-specific types like `Message` rather than just rendering from the API types directly like `Post`, so we can use our own representation without having to fight the API library.

**Comment by jtdaugherty** [comment]
(I'll also add that this approach could dovetail nicely with an attempt at dealing with #389 since the same `newtype` could also be used to replace troublesome unicode characters at render time.)

**Comment by jtdaugherty** [comment]
This is now fixed in `develop`. Escape characters are expanded to `<ESC>` in user input and content from the server, so you'll get a nice wart in any offending text. I'm going to put out a release with this fix shortly. Thank you for the report!
