### ISSUE TITLE
Add support for Multi-Factor Auth (MFA Tokens)

### ISSUE THREAD

**Issue by oblakeerickson** [matterhorn-chat/matterhorn#409]
Just creating this issue as a tracking topic in hopes that someday support for MFA tokens could be added.

Here is the error I just received when trying to authenticate with our mattermost server that requires multi-factor auth:

```
Error: MattermostError {mattermostErrorId =                                                                                  
"ent.mfa.validate_token.authenticate.app_error",                                                                             
mattermostErrorMessage = "Error trying to authenticate MFA                                                                   
token", mattermostErrorRequestId =                                                                                           
"mtoots3me7fzmenjtiw75w4x5o", mattermostErrorStatusCode =                                                                    
401, mattermostErrorIsOAuth = False}                                                                                                                                                                                                 
```

**Comment by jtdaugherty** [comment]
Thanks! Since we don't keep tickets open until a feature has a concrete implementation plan, I'm closing this in lieu of a new wiki page at

https://github.com/matterhorn-chat/matterhorn/wiki/Multi-Factor-Authentication

That page is an invitation to anyone who wants to take on the next steps to help us get closer to implementing the feature. It is unlikely to be on the core development team's roadmap soon, but any contributions to help would be great!

For more context on the closing of this ticket, please see

https://github.com/matterhorn-chat/matterhorn/blob/master/PRACTICES.md#design
