### ISSUE TITLE
Teammate name display client-side configuration

### ISSUE THREAD

**Issue by robbiemcmichael** [matterhorn-chat/matterhorn#416]
It would be nice to add a client-side setting in Matterhorn for overriding the way teammates' names are displayed. The Mattermost web client supports the following options:

- Show username
- Show nickname if one exists, otherwise show first and last name
- Show first and last name

Currently there is a concept of a display name in Matterhorn, but it has some issues:

- It only obeys the server-side setting, which most users won't be able to change
- When `nickname_full_name` is used on the server-side setting, it actually displays nickname and username instead (which seems an odd combination to me even if it was intentional)
- There is an issue with opening a DM from the channel list via a display name (see #415)

**Comment by jtdaugherty** [comment]
> It only obeys the server-side setting, which most users won't be able to change 

As of 9a50f080915ab9efe3a4e012b75452f5552c35ac, `matterhorn` will now respect the account-specific setting for this if that setting is set to either Username or Nickname/first/last name. Matterhorn will pick up on the change in real time without a restart, so to observe the behavior, run Matterhorn and change the setting in the web browser for the same account and Matterhorn will redraw accordingly.
* Note that this change does not add support for the "full name" setting yet, since that is part of a larger change that will take more time to make.
* Also note that this change does not add a Matterhorn-specific client setting because the server already stores account settings set by the browser that we should honor.
* Finally, note that this change does not add a settings UI to manage such settings, but we eventually want that; it's just too big a change to add right now just to make this behavior better.

> When nickname_full_name is used on the server-side setting, it actually displays nickname and username instead (which seems an odd combination to me even if it was intentional)

This is mostly because full names (i.e. with spaces) interact poorly with the completion logic, but I will investigate that. Nicknames suffer from the same problem if they contain spaces. The issue with "display names" has been that you can't just display them: you have to recognize them as input in a variety of settings, and we haven't done that work for full names because whitespace makes that tedious. Anyway, I'll investigate.

**Comment by robbiemcmichael** [comment]
I've got a change that implements the three display options in Matterhorn's configuration file. It ended up being a bit more invasive than I was expecting, but it seems to be working. I'm just cleaning up some of the implementation but then I'll push it to GitHub so you can have a look at it and decide whether you want to turn it into a feature branch.

> Also note that this change does not add a Matterhorn-specific client setting because the server already stores account settings set by the browser that we should honor.

It might be worth asking whether Matterhorn should use the client settings that are stored server-side. My personal opinion is that Matterhorn has a configuration file and so all settings should be stored there so there is only one place to go to change settings. This would also allow you to have different settings for the web client and Matterhorn (e.g. usernames only in Matterhorn, but nickname/full name in the web client).

**Comment by jtdaugherty** [comment]
> It might be worth asking whether Matterhorn should use the client settings that are stored server-side. My personal opinion is that Matterhorn has a configuration file and so all settings should be stored there so there is only one place to go to change settings.

Our aim is to respect options stored server-side in the web client to ensure that Matterhorn's behavior is (to the extend that we aim to have parity) the same as that of the web client. As a result, we only use the configuration file for settings that are not common to both clients or are not storable as server-side preferences.

Since this is already a web-client-configurable, server-side preference, we'll want Matterhorn to honor (and, ultimately, manage) that instead of adding another configuration file option.

**Comment by jtdaugherty** [comment]
Since we've gone as far as we can go with this right now, I'm closing this in favor of the newer issue, #420. Thank you for the report!
