### ISSUE TITLE
After editing with $EDITOR, switch to single-line mode automatically

### ISSUE THREAD

**Issue by rightfold** [matterhorn-chat/matterhorn#419]
Steps to reproduce:

 1. Hit M-k to compose a message in the preferred editor.
 2. Compose a multi-line message, save the file, and exit the editor.

Preferred behavior:

The message field is in single-line mode, and I can submit it by hitting return. This is the most common use-case, at least for me.

Actual behavior:

The message field is in multi-line mode, and I first have to hit M-e before I can submit the message.

**Comment by jtdaugherty** [comment]
This is now fixed so that the multiline mode is *not affected* by the invocation of `$EDITOR`, meaning that if your input box was in multiline mode when you hit `M-k`, it would remain so when you returned, and if it wasn't in multiline mode, the it would not be in multiline mode when you returned. This is the least surprising behavior that also does what you want, since someone could have the intention of continuing to edit after returning from the editor.

Thanks for the report!

**Comment by rightfold** [comment]
Amazing! ❤️
