### ISSUE TITLE
Use user display names when rendering

### ISSUE THREAD

**Issue by jtdaugherty** [matterhorn-chat/matterhorn#443]
(Depending on the user display name preference.)

**Comment by kquick** [comment]
Both channels and users have a "name", which is used as the reference, and a  "displayName" value, which is what should be shown when rendering messages and/or the sidebar.  There is also an ID for both, so the primary purpose of the "name" seems to be for auto-completion/typing because it uses a restricted character set for disambiguating the input token identification.

To maintain consistency with the Web UI, auto-completion is done using the primary "name" of the channel or user (when prefixed with a ~ or @, respectively), and this is the value that should be submitted in any messages posted to the channel.

Received messages should be scanned for the "name" of a user or channel, and (prior to rendering layout), replace the "name" with the corresponding "displayName" (for channels, this is absolute, but for users this may be a full name or a nickname, depending on the preferences).

The color value used for users should be stable (e.g. use the "name" or id as the input for color selection).

The sidebar should change to show the "displayName" of the channels (it should already be showing the configuration-driven display name for users), and the ~ should be removed (possibly TBD: is there a different sigil for private channels?).

Autocompletion suggestions should show both the "name" (which will be used for the completion) and the "displayName" (which is what the user normally sees).   Message preview should show the "displayName", but the message entry editor should show the "name".

**Comment by jtdaugherty** [comment]
> Both channels and users have a "name", which is used as the reference, and a "displayName" value, which is what should be shown when rendering messages and/or the sidebar. There is also an ID for both, so the primary purpose of the "name" seems to be for auto-completion/typing because it uses a restricted character set for disambiguating the input token identification.

Current status: Matterhorn shows channel display names. Matterhorn's display of users depends on the server configuration settings (username or nickname).

> To maintain consistency with the Web UI, auto-completion is done using the primary "name" of the channel or user (when prefixed with a ~ or @, respectively), and this is the value that should be submitted in any messages posted to the channel.

Current status: Matterhorn supports completion based on any portion of channel or user names/nicknames/display names.

> Received messages should be scanned for the "name" of a user or channel, and (prior to rendering layout), replace the "name" with the corresponding "displayName" (for channels, this is absolute, but for users this may be a full name or a nickname, depending on the preferences).

Current status: we don't do any replacements. I'm not excited about implementing it, partly because I don't care for the web client's behavior, and also because nobody has requested it. But if it becomes an issue, we can open a new ticket about it.

> The color value used for users should be stable (e.g. use the "name" or id as the input for color selection).

This is currently the case.

> The sidebar should change to show the "displayName" of the channels (it should already be showing the configuration-driven display name for users), and the ~ should be removed (possibly TBD: is there a different sigil for private channels?).

This is currently the case.

> Autocompletion suggestions should show both the "name" (which will be used for the completion) and the "displayName" (which is what the user normally sees). Message preview should show the "displayName", but the message entry editor should show the "name".

This is mostly currently the case. I'm not sure I understand the second sentence, though.

Given the age of this item and my desire to clean up old tickets, I'm going to close this as mostly done. But like I said, if any of the elements of this become problematic, we can just open more specific tickets.
