### ISSUE TITLE
channel name change not updated

### ISSUE THREAD

**Issue by amaloz** [matterhorn-chat/matterhorn#474]
When a channel name has been changed, it doesn't seem to get reflected in `matterhorn`, whereas with the `mattermost` web client I see the updated channel name.

**Comment by jtdaugherty** [comment]
Thanks for the report!

**Comment by kquick** [comment]
Matterhorn is currently rendering the "name" and not the "displayName" because the former is also how channels are referenced (e.g. by including `@chan` in a message).  However, the WebUI is showing the "displayName", and the latter is what the `/rename` command changes, which is why the new name was not being displayed.

Bug report https://github.com/matterhorn-chat/matterhorn/issues/443 specifies the changes needed for Matterhorn to transition to using "displayName" like the WebUI.  In the interim, the channel header will be modified to show both the "name" and the "displayName" for the current channel (both are already displayed on the `/join` command dialog window).

Also note that the web UI allows changing the channel "name" as well as the "displayName".   In Matterhorn, the `/rename` command provided by the server changes the "displayName", and https://github.com/matterhorn-chat/matterhorn/issues/475 has been created for allowing changing the channel "name" via Matterhorn.

**Comment by jtdaugherty** [comment]
Since this ticket's behavior is not actually a bug given our current feature set, I'm closing in lieu of a new related feature ticket, https://github.com/matterhorn-chat/matterhorn/issues/522.
