### ISSUE TITLE
Windows port of Matterhorn

### ISSUE THREAD

**Issue by Zero3K** [matterhorn-chat/matterhorn#479]
It would be nice if someone made one that allows for the displaying of page previews, etc.

**Comment by jtdaugherty** [comment]
Can you say a bit more about what you are looking for? I don't understand how the title of this issue is related to the body. :)

**Comment by Zero3K** [comment]
I just want a version of it for Windows 7 and up that can display previews of links, etc. (basically, what the web client for Mattermost is capable of). If that's not possible, then a console application would be fine.

**Comment by jtdaugherty** [comment]
Okay, thanks for the extra detail.

At present, a Windows port of Matterhorn is not possible since it uses libraries that fundamentally assume a Unix terminal. Until and unless those libraries are ported to also work on Windows, Matterhorn will remain a Unix application.

As far as link previews are concerned, if you're talking about graphical previews, then the web application is the better choice. Since Matterhorn is deliberately designed to avoid such graphical interfaces, we don't have any plans of ever adding that kind of feature. However, if you just mean some other ability to open links using a graphical application, Matterhorn already has that in the form of the "URL open command," which is configurable. By using that the local web browser can be used to open links from within Matterhorn, for example.

**Comment by Zero3K** [comment]
Not even Cygwin can be used to port it?

**Comment by jtdaugherty** [comment]
At present we do not support Cygwin. I don't know enough about it to say whether it is possible technically, though.

**Comment by Zero3K** [comment]
I am trying to compile it under Windows and have ran into the errors mentioned at:

https://pastebin.com/A0MsKstC

**Comment by jtdaugherty** [comment]
Yes, right now Matterhorn has some transitive dependencies on the `unix` package, which is naturally not going to work on Windows.

**Comment by Zero3K** [comment]
Is there any way around it?

**Comment by jtdaugherty** [comment]
Aside from running Unix software on Windows such as [this](https://docs.microsoft.com/en-us/windows/wsl/install-win10), I don't think so.

**Comment by Zero3K** [comment]
I am using Windows 7.

**Comment by Zero3K** [comment]
Could that change anytime soon? Or maybe you could help the developer of Ripcord with getting it to support Mattermost.

**Comment by jtdaugherty** [comment]
@Zero3K the situation I described above still has not changed and is very, very unlikely to; we don't have the resources to change it, or the intention, and I don't think it's likely that any community contributors will step forward to overhaul terminal support on Windows. Our best recommendation for Windows users is to use the official client. Sorry!
