### ISSUE TITLE
Support installation via Homebrew

### ISSUE THREAD

**Issue by dAnjou** [matterhorn-chat/matterhorn#482]
Referring to https://brew.sh/.

Would be nice to have one 🙂

**Comment by MartinDelille** [comment]
> Source builds of releases can be done with released versions of the dependencies as found on Hackage.

You mean I can download the full source from Hackage? Do you have an URL to provide?

**Comment by jtdaugherty** [comment]
I hesitate to go into more detail on this for the following reason: Haskell packages built from source via Homebrew does not seem like a good idea to me, and I doubt it's even a good way to do it. Matterhorn is definitely available on Hackage via source, as are all of its many dozens of Haskell dependencies, but I seriously doubt that will help you, because I don't think using Homebrew to do a build that way is idiomatic. I'd need to do more investigation, but judging by your question it sounds like you are not yet familiar with how Haskell programs are built.

Ultimately I suspect that building Matterhorn from source via Homebrew will not be worthwhile or even a good way to go, and that binary-only installation will be the most sensible thing to do.

**Comment by MartinDelille** [comment]
I'm not familiar with Haskell at all.

I'm fine with my tap. Feel free to come back to me if you want help about a brew formula which could be a good way to install for people like me!

**Comment by jtdaugherty** [comment]
Okay, will do, @MartinDelille - thank you!

**Comment by MartinDelille** [comment]
I managed to make another formula that build from the source here: https://github.com/Homebrew/homebrew-core/pull/36196

Unfortunately it fails *Homebrew* build system because of the ssh link in https://github.com/matterhorn-chat/matterhorn/blob/master/.gitmodules (in my opinion)

Would you mind if I send you a PR changing them to https?

**Comment by jtdaugherty** [comment]
@MartinDelille The submodule URLs do not need to change. Instead, please do the build without using the submodules at all. To make that work, the `cabal.project` file should be removed prior to the build.

Looking at the build script you have, am I correct in saying that all it does is install the `matterhorn` binary but none of the other documentation/script/syntax files?

**Comment by tgy** [comment]
@MartinDelille do you plan on making progress on this? it would be nice to have a formula that works out of the box!

**Comment by jtdaugherty** [comment]
@tgy For what it's worth, I think the most appropriate way to move forward on this ticket is to make a Homebrew tap based on the binary Matterhorn releases. I believe @MartinDelille was using an approach based on the Haskell source itself. I expressed some concerns about that above.

On the development team, we have not had time to make this feature a priority, and we also haven't gotten enough user interest to move it up the priority list. So at this point I think the only way this feature will get developed is if someone wants to volunteer to work on it. If so, that would be great! And if so, it would be important to base the Homebrew installation on the binary releases and to work with us to make sure we are willing to sign up to maintain the Homebrew formula going forward.

**Comment by MartinDelille** [comment]
Homebrew formula need to let the user compile himself the code.

I made a first version here but it is not functional because it doesn't add `matterhorn` executable in the path: https://github.com/MartinDelille/homebrew-tap/blob/master/Casks/matterhorn.rb

I need to understand how to do it with a cask so I asked here: https://discourse.brew.sh/t/add-a-cask-formula-executable-to-usr-local-bin/6762

Any way, a regular homebrew formula would be more appropriate because it is always better use homebrew's pipelines and bintray binaries or even to let the user compile himself than passing binaries to the user (which doesn't guaranties it is malicious code free).

It also help to have a safer build which is always better if you look for new contributors.

**Comment by jtdaugherty** [comment]
> Any way, a regular homebrew formula would be more appropriate because it is always better use homebrew's pipelines and bintray binaries or even to let the user compile himself than passing binaries to the user (which doesn't guaranties it is malicious code free).

Unfortunately that won't quite work for this project, because we only support a limited range of versions of the Haskell compiler (and I have no idea which versions of GHC come with Homebrew). In addition, building Matterhorn from source requires building hundreds of Haskell dependencies, and those usually aren't in Homebrew at all. Even if they were, there are likely to be version conflicts.

> it is always better use homebrew's pipelines and bintray binaries or even to let the user compile himself than passing binaries to the user (which doesn't guaranties it is malicious code free).

I'm not sure how to rectify this comment with the fact that there are a great many binary packages in Homebrew already. How can I trust them?

> It also help to have a simpler build which is always better if you look for new contributors.

I agree, although I don't think supporting Homebrew improves the build simplicity. Right now our build is very simple if you just install the Haskell build tools.

**Comment by dAnjou** [comment]
Let's not overthink this 🙂The biggest advantage of homebrew is that people get updates automatically. To achieve that a custom tap or a cask is perfectly fine.

If someone feels like making it real nice using a formula then they may go ahead but I don't see any issue with distributing the binary built by the members of the project.

If I get the approval of a member I might even issue a cask PR myself.

**Comment by dAnjou** [comment]
I've created a cask: https://github.com/dAnjou/homebrew-cask/pull/1 (this is a PR to master within my fork, just to show what the real one would look like).

With your blessing I'd open a real one.

**Comment by jtdaugherty** [comment]
> With your blessing I'd open a real one.

Works for me!

> Oh, and the releases are stable?

Yes.

**Comment by dAnjou** [comment]
Oh, and could you provide SHA256 sums with the next release?

**Comment by jtdaugherty** [comment]
@dAnjou filed, thanks: https://github.com/matterhorn-chat/matterhorn/issues/552

**Comment by MartinDelille** [comment]
@jtdaugherty Ok I didn't knew the complexity of the build dependency required by matterhorn but I agree with you that handling dependencies in Homebrew can be hell.

@dAnjou Nice job : you add the line I was missing to make it work! I updated my cask and it work like a charm! 

Regarding the SHA256, do you really need to provide it? Testing a cask installation with a bad sha output the real sha which make it easy to update.

It's the first time I see matterhorn in action because last time I tried I had a certificate issue which made impossible for me to test it (cf #263). Thank you for this amazing work!

**Comment by MartinDelille** [comment]
Rejected :( https://github.com/Homebrew/homebrew-cask/pull/76235#event-2984128179

The cask is available through my task: `brew cask install martindelille/tap/matterhorn`

**Comment by dAnjou** [comment]
> Rejected  : [Homebrew/homebrew-cask#76235 (comment)](https://github.com/Homebrew/homebrew-cask/pull/76235#event-2984128179)

Not a final decision as far as I understand. We could still make a point. But I can't really do that as I've absolutely zero Haskell experience and haven't even tried building it from source.

**Comment by jtdaugherty** [comment]
I just commented on the Homebrew ticket.

**Comment by jtdaugherty** [comment]
This now seems to be working. I was able to run:
```
$ brew cask install matterhorn
```
and get a working Matterhorn installation. Can others take a look, too?

**Comment by MartinDelille** [comment]
I removed `matterhorn` from my tap and it works like a charm!

You managed to convince the homebrew maintainer which is not an easy task, well done!

**Comment by dAnjou** [comment]
Great 🎉 

Next up: improving the cask so that it contains the other files as well for convenient notification setup 🙂  (that's another story though)

**Comment by jtdaugherty** [comment]
What other files? Won’t it automatically contain everything in our binary release tarball?

**Comment by jtdaugherty** [comment]
Here's what I see:
```
$ ls /usr/local/Caskroom/matterhorn/50200.6.0/matterhorn-50200.6.0-Darwin-x86_64/
total 40416
-rw-r--r--@   1 cygnus  staff    46K Jan 15 08:41 CHANGELOG.md
-rw-r--r--@   1 cygnus  staff    41B Jan 15 08:41 COMMIT
-rw-r--r--@   1 cygnus  staff    46K Jan 15 08:41 COPYRIGHT
-rw-r--r--@   1 cygnus  staff    15K Jan 15 08:41 README.md
drwxr-xr-x@   4 cygnus  staff   128B Jan 15 08:41 docs/
drwxr-xr-x@   5 cygnus  staff   160B Jan 15 08:41 emoji/
-rwxr-xr-x@   1 cygnus  staff    20M Jan 15 08:41 matterhorn*
drwxr-xr-x@   3 cygnus  staff    96B Jan 15 08:41 notification-scripts/
drwxr-xr-x@ 136 cygnus  staff   4.3K Jan 15 08:41 syntax/
```

**Comment by jtdaugherty** [comment]
Something else I noticed is that when I run `matterhorn` out of the cask installation, I get an OS X dialog box about an untrusted binary. I don't know of a nicer way to bypass that than to go find the original binary in the Finder, open it with Command-Open, and then trust it. That's going to be an unpleasant roadblock for users.

**Comment by MartinDelille** [comment]
Can someone explain how the `notification-scripts` works?

**Comment by jtdaugherty** [comment]
@MartinDelille Let's move that discussion to:

https://github.com/matterhorn-chat/matterhorn/issues/554
https://github.com/matterhorn-chat/matterhorn/issues/555

**Comment by MartinDelille** [comment]
I subscribed!

**Comment by jmcvaughn** [comment]
> Something else I noticed is that when I run `matterhorn` out of the cask installation, I get an OS X dialog box about an untrusted binary. I don't know of a nicer way to bypass that than to go find the original binary in the Finder, open it with Command-Open, and then trust it. That's going to be an unpleasant roadblock for users.

@jtdaugherty: This is due to Gatekeeper. Without becoming an "identified developer" or disabling Gatekeeper, the best methods I believe are:

- Use the `--no-quarantine` option during installation: `brew cask install --no-quarantine matterhorn`. Note that this **bypasses** Gatekeeper rather than creating and enabling an assessment rule for the application, so users need to be sure they trust you :) :
```
% spctl -a /usr/local/bin/matterhorn
/usr/local/bin/matterhorn: rejected
```

- Use spctl to create a rule. As I use the first method, I haven't tested this; see `man 8 spctl`.

**Comment by jtdaugherty** [comment]
Thank you, @jmcvaughn - I didn't know about either of those approaches!

**Comment by jtdaugherty** [comment]
@nlhomme I can see how it might appear that this is done, but re-reading the conversation we had above, I'm not so sure that is the case. Unless something has changed that I'm not aware of, there are some potential issues (discussed above) about the build of Matterhorn that is currently available on Homebrew.

I'm not really sure how to proceed, frankly. If I had the time, I'd personally maintain a Matterhorn build for Homebrew. But I don't, so it's helpful if someone else wants to put energy into that. But having a third-party build in Homebrew is misleading if I am not its maintainer unless its maintainer is *very* committed to keeping it up to date, working, and playing nice in the macOS ecosystem. I think the gatekeeper issue ultimately probably needs to be addressed, and I'd want to get an updated assessment from others on this ticket about who is actively committed to maintaining Matterhorn distribution via Homebrew. If it's going to be spotty, I'd prefer not to have it in Homebrew at all out of concern that it would just become stale.

**Comment by jtdaugherty** [comment]
Due to limited resources and time on my part, I am going to close this as something I cannot commit to supporting. For now, any Homebrew availability of Matterhorn is unofficial and unsupported (by me), although of course I would be happy to hear from people who run into issues using those versions of Matterhorn.
