### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by nivex** [matterhorn-chat/matterhorn#488]
Memory usage of matterhorn-50200.1.2-Ubuntu-x86_64 on startup is unacceptably high. On my VPS:
```
nivex@triton:~$ top -b -oRES | head -n20
top - 17:40:34 up 224 days,  3:15, 13 users,  load average: 0.09, 0.06, 0.01
Tasks: 186 total,   1 running, 146 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.6 us,  0.5 sy,  0.0 ni, 97.6 id,  0.0 wa,  0.0 hi,  0.0 si,  0.3 st
KiB Mem :  2035496 total,    32316 free,  1085680 used,   917500 buff/cache
KiB Swap:   262140 total,   243444 free,    18696 used.   797536 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 4909 nivex     20   0  1.000t 230188  29804 S  0.0 11.3   0:08.10 matterhorn
 5357 mysql     20   0  817680 163660   7340 S  0.0  8.0 115:31.21 mysqld
20191 root      20   0  179424  97756   7652 S  0.0  4.8   0:10.15 spamd child
20189 root      20   0  162280  84724   7464 S  0.0  4.2   0:12.73 spamd
20192 root      20   0  162280  79584   2324 S  0.0  3.9   0:00.05 spamd child
 3609 root      20   0  134364  50108   5576 S  0.0  2.5 175:51.49 linode-longview
31663 matterm+  20   0  580604  49316  11340 S  0.0  2.4  70:29.78 mattermost
12120 nivex     20   0  203452  45528  15632 S  0.0  2.2  89:45.05 weechat
14852 nivex     20   0  396532  36156   8920 S  0.0  1.8  35:13.23 supybot
19094 nivex     20   0  556588  34628  11736 S  0.0  1.7   0:03.71 apache2
11582 hope      20   0  180240  30312   4528 S  0.0  1.5 112:16.76 weechat
19119 www-data  20   0 1239448  22808  11476 S  0.0  1.1   0:39.92 apache2
16195 pdns      20   0  369212  22504   6028 S  0.0  1.1  16:35.54 pdns_recursor
```
After it has been running for some hours it will have grown such that all of swap is used.

**Comment by jtdaugherty** [comment]
It is normal for Matterhorn to increase memory residency over time, and it is normal for Matterhorn to use 200-300 MB of RAM at startup and at any given time. To some extent the memory footprint is a consequence of our choice of programming language, and Matterhorn will definitely use more memory as it is left running, but the rate of that increase shouldn't be unreasonable. It's possible there's a leak, so we'd definitely like to determine whether there is one.

It would help if you could give us some context for the situation. How many channels are you subscribed to? Are they very active?

**Comment by nivex** [comment]
I'm still evaluating Mattermost, so there are only two channels and not very active at all.

**Comment by jtdaugherty** [comment]
Okay. Thank you for the report!

**Comment by jtdaugherty** [comment]
Looking back on this ticket again after a while, I'm going to close it. The base memory requirement for Matterhorn is not under our control past a certain point due to the Haskell runtime system's behavior. If there is a genuine *leak*, we would be happy to investigate and address that, but this ticket does not report a leak (although I thought it might when I changed the title last year). Please re-open or file a new ticket if you observe a leak. Bear in mind that Matterhorn will definitely use more memory over time since it deliberately does not drop old messages, so a leak would probably manifest as a larger-than-anticipated change in residency out of proportion to the amount of message traffic.
