### ISSUE TITLE
Reactions briefly disappear when updated

### ISSUE THREAD

**Issue by immindich** [matterhorn-chat/matterhorn#509]
When somebody reacts to a message that already has reactions associated with it, Matterhorn will first render the message without any reactions and then display the updated version. This causes the given message, along with all of the messages above it, to move down a line and then move back up again. This is visually distracting when many people react to the same message in a short span of time. It would be better if this intermediate state did not happen and Matterhorn went directly to displaying the updated reactions.

**Comment by kquick** [comment]
Also note that this is even more acute when there are some attachments to the message (e.g. images), because each attachment gets its own line on rendering, and the addition of a reaction drops these on the first redraw as well.

For a one-line message with two attachments and some reactions, the effect is 4 lines collapsed to 1 line, and then each attachment as well as the reactions seems to be a separate update, so there are 3 additional redraws with each adding back another line.

**Comment by jtdaugherty** [comment]
I can't reproduce this on `develop` and I also haven't seen this happen in a long time. Since I don't know what cause this in the first place, it's impossible to say what "fixed" it. @kquick have you seen this recently?

**Comment by kquick** [comment]
I have tested this just now and cannot reproduce it either, so I think it has been resolved somehow in the interim.  I think this issue can be closed.

**Comment by jtdaugherty** [comment]
Okay, thanks!
