### ISSUE TITLE
View Message wrapping/scrolling

### ISSUE THREAD

**Issue by kquick** [matterhorn-chat/matterhorn#511]
Currently the window used to "v"iew message details will show the message text without wrapping, followed by a horizontal border and all of the reactions for that message.  The window can be scrolled both vertically and horizontally.

Up through at least mid-July on the `develop` branch, the horizontal scrolling scrolls the entire window, so the reactions are scrolled off the left side when viewing a long message.

Additionally, this window was initially intended to assist with viewing code segments which are truncated at the right border in the normal "Messages" window.  Normal text messages do *not* often contain newlines, so this makes viewing a long message *without* code segments awkward, especially now that this window displays reactions.

There should be better handling here.  The exact behavior is still TBD and there may be some prototyping of different approaches needed, but some of the goals are probably:
* The reactions area is not horizontally scrolled
* The entire window can be vertically scrolled
* Non-code text is wrapped normally
* Code text (e.g. between single or triple backticks) is not wrapped and can be viewed with scrolling.

**Comment by jtdaugherty** [comment]
In a discussion with @kquick and @immindich, we explored solving these problems with a new tabbed interface, e.g.,
```
+------------------------------------------+
| Message | Reactions |                    |
+------------------------------------------+
|                                          |
|                                          |
|                                          |
+------------------------------------------+
```
where rather than showing the message *and* the reactions in a single scrollable area as we do now, they'd be shown separately in a tabbed window so the user could select between them and scroll each more naturally.

As part of that conversation we also established some other conditions of satisfaction for the work:
* We need to ensure that the message view mode (both current and future) is dynamic enough to display the message and its metadata *as it changes while the dialog box is open*.
* We explicitly don't want to worry right now about calling out state deltas since the dialog box was open (e.g. new reactions). We want to make sure those state changes are reflected, but we don't need to worry about calling them out in any special way (the way we do with e.g. the New Messages lines).
* If the message being viewed was deleted since the dialog box was opened, we need to indicate that clearly since once the user closes the dialog box, the message will not be accessible again.
* We want to make sure that any tabbed window infrastructure built for this work is re-usable in case we want to use this UI idiom again, and we want to make sure that infrastructure gracefully handles more tabs than can fit in the visible window.

**Comment by jtdaugherty** [comment]
On the topic of whether the content of the message view window is currently dynamic, it looks like that's highly unlikely because we have the `ChatState` field
```haskell
_csViewedMessage :: Maybe Message
```
which is going to have to be updated whenever the message changes state, and that's almost certainly not going to happen.

**Comment by kquick** [comment]
Just to clarify, I'm interpreting your final statement above as: "the `csViewedMessage` is almost certainly not happening now, but we intend to make that occur as part of these changes."

**Comment by jtdaugherty** [comment]
My statement is more that "`csViewedMessage` includes a message, not a message ID, so from that I conclude that it does not get updated by current message-maintaining events." What I'd like to do is leave that alone for now, and fix that in a separate pass.

**Comment by kquick** [comment]
Ah, that makes sense.  Yes, I agree: it's orthogonal to the tab view.

**Comment by jtdaugherty** [comment]
Thanks; I've made #526 as a reminder to take care of that.

**Comment by jtdaugherty** [comment]
Another thing to consider: some kind of help indication in the tabbed window about the keybindings available.

**Comment by jtdaugherty** [comment]
For posterity: this work is taking place on the `feature/view-message-tabs` branch.

**Comment by jtdaugherty** [comment]
It looks like this ticket got overlooked; I think all of the items called out above have been implemented.
