### ISSUE TITLE
Use a dedicated color for current user

### ISSUE THREAD

**Issue by wiruzx** [matterhorn-chat/matterhorn#514]
Sometimes it's hard to tell if you have a new message just by glancing at the chat. 
Especially if the length of your names matches.

![screenshot](https://i.imgur.com/JYC4LJv.png)

It'd be great if we had a different color, or any other way to tell apart current user and the counterpart.

**Comment by kquick** [comment]
Hi @wiruzx.  

Thank you for bringing this up.  I have a couple of questions just to verify the behavior you are encountering:

Are you seeing the same color for all users, or just a couple? As background: Matterhorn should be using different colors for users, but the heuristic for the color to use is based on a hash bucket computed from the username.  Due to the limited number of colors, there will be multiple users per bucket, but you should be seeing some variations.  The hash computation is intended to be stable so that a user's coloration does not change between channels or sessions.

Also, I wanted to check to make sure you are getting a "---- New messages ---" marker line in the channels to indicate the new messages.  This is one way to be aware of new messages, and there's also the ability to run a notification script (via the `activityNotifyCommand` configuration element).

**Comment by wiruzx** [comment]
@kquick Hey!

Sorry for confusion, I should've given more context in the issue.

I'm seeing different colors for different users. But since we have limited amount of colors, some users will have the same color as mine.

So my idea was to use hardcoded dedicated color for current user. Which will always be different from colors calculated based on username.

As for "new messages" separator, I'm pretty sure it doesn't appear if the message received in open chat, at least for me.

**Comment by kquick** [comment]
OK, thanks for the clarification.  

I like the idea of distinguishing the current user's comments from others in the channel, although I'm not sure that will help to identify "new" messages unless the new message is a response to your message.

I'm also a bit hesitant to dedicate an entire color to the current user, given that the colors available are such a limited resource.  There may be some other types of markup that we could use to indicate this, so I think we'd probably want to experiment with some different markups to see what is the best visual integration that keeps the readability level high.

Is this something you were considering contributing the changes for?  That's certainly not required, but if you were interested I wanted to make sure we worked with you instead of duplicating efforts.

**Comment by wiruzx** [comment]
> I'm not sure that will help to identify "new" messages unless the new message is a response to your message.

I was trying to say that in some scenarios it's easy to miss if you got a new message.
For example if you have 1:1 chat with someone, you sent a message, and left the chat open.
When you come back, you'll see that your message is not the last one. But when colors are the same, it's a bit less noticeable.

>I'm also a bit hesitant to dedicate an entire color to the current user, given that the colors available are such a limited resource.

Makes sense. 

> There may be some other types of markup that we could use to indicate this, so I think we'd probably want to experiment with some different markups to see what is the best visual integration that keeps the readability level high

Having dedicated color was very appealing idea, because it would look clean and won't create visual clutter. But yeah, if we can't use the color, may be adding some unicode character will do?

> Is this something you were considering contributing the changes for?

Yeah, I was thinking to make a PR, but it worth to discuss first :)

**Comment by kquick** [comment]
> > I'm not sure that will help to identify "new" messages unless the new message is a response to your message.
> 
> I was trying to say that in some scenarios it's easy to miss if you got a new message.
> For example if you have 1:1 chat with someone, you sent a message, and left the chat open.
> When you come back, you'll see that your message is not the last one. But when colors are the same, it's a bit less noticeable.

That's reasonable, I just wanted to make sure this was addressing your core concern in case there was a different way to achieve that.  

Your point about the direct user channel is especially compelling in this case.

> 
> > I'm also a bit hesitant to dedicate an entire color to the current user, given that the colors available are such a limited resource.
> 
> Makes sense.
> 
> > There may be some other types of markup that we could use to indicate this, so I think we'd probably want to experiment with some different markups to see what is the best visual integration that keeps the readability level high
> 
> Having dedicated color was very appealing idea, because it would look clean and won't create visual clutter. But yeah, if we can't use the color, may be adding some unicode character will do?

I had been thinking of some other decorator possibilities; for example: showing the current user's name in bold.  

A unicode marker might work, although there's less broad support for unicode in terminals (much better these days than it used to be, but still a consideration), and multi-character unicode is especially problematic due to inconsistencies in the rendered width, so if you do end up trying a unicode or similar marker, using something more common and less exotic is probably adviseable.

> > Is this something you were considering contributing the changes for?
> 
> Yeah, I was thinking to make a PR, but it worth to discuss first :)

Cool, thanks for discussing it first, and contributions are definitely appreciated!  Please feel free to experiment with different types of markup to find one (or even a couple of alternatives) that you think works well and then we can try out your branch on different configurations and terminals to see how well that is handled by those different configurations.

**Comment by wiruzx** [comment]
Will do, thanks!

**Comment by jtdaugherty** [comment]
If this is going to be done, I suggest it be done using color theme attribute names. Right now it is already possible to configure which colors go with which hash buckets. If we're going to support a configurable attribute for "self" then I would like to see a color theme setting for that (which defaults to the current behavior -- hashing of the current username -- to choose a color if it isn't specified). This also means that by default current users would be unaffected by a future release that rolls this out, and folks like the reporter of this ticket who want this behavior can get it (and we should document how to do so if the feature is added).

**Comment by jtdaugherty** [comment]
@wiruzx are you still planning on working on this? If not, I'm happy to take it on.

**Comment by wiruzx** [comment]
@jtdaugherty Yeah, I'm still working on it, just have busy times at work, sorry about that.
Actually I think I'd need to resolve #439 first, as a preparation for this one, if you don't mind :)

**Comment by jtdaugherty** [comment]
Feel free - although that one *might* actually already be fixed, so be aware of that.

**Comment by jtdaugherty** [comment]
@wiruzx I wanted to check in again on this ticket. Last year you mentioned above that you were working on it. If you still have an intention to implement this feature, it would be helpful for us to work out a timeline for that. If not, someone else can take it on.

**Comment by wiruzx** [comment]
@jtdaugherty Hey, sorry about that. I didn't find time to work on this lately. But I'd still love to finish it. Can you give me a couple of weeks? If I don't finish it in that time, I'll reassign it from myself. Thanks!

**Comment by jtdaugherty** [comment]
How about Feb 29 as a target date?

**Comment by wiruzx** [comment]
Sounds good!

**Comment by jtdaugherty** [comment]
Okay, great. I have it on my calendar to check on this ticket right after that point.

**Comment by wiruzx** [comment]
Hey, 
I've created two pull requests for this issue. 
I assume only one of them should be merged.

---------------

As discussed, I've added ability to add attributes for current user's name. #567

Here how it looks in bold:
<img width="177" alt="Screenshot 2020-02-23 at 9 32 07 pm" src="https://user-images.githubusercontent.com/3197387/75122605-5c7d7e00-5697-11ea-8bb7-7061bd42fa4e.png">

And here's underline
<img width="174" alt="Screenshot 2020-02-23 at 9 31 19 pm" src="https://user-images.githubusercontent.com/3197387/75122602-57203380-5697-11ea-9fea-c95abbc085a3.png">

I tried to play with the other attributes, the only one that had any effect was `standout` which was standing out too much.

----------------

I've also tried to tackle this problem the other way, by introducing the configurable suffix to your username #568

To be honest I'm more in favour of this approach, as it looks much nicer in the message list. 

<img width="127" alt="Screenshot 2020-02-24 at 12 00 40 am" src="https://user-images.githubusercontent.com/3197387/75122740-ba5e9580-5698-11ea-9f34-ab4d07fa84bb.png">

It will also allow for users whose terminal doesn't support unicode, to put whatever they want such as " (you)", so there is clear distinction between usernames.

------------------

@jtdaugherty @kquick Please let me know what do you guys think

**Comment by jtdaugherty** [comment]
Thanks for your work, @wiruzx! I prefer an attribute-based approach rather than a suffix-based one.

For an attribute-based approach, I had imagined that the attribute(s) and style(s) to use for the "current" user would be configurable by setting a special attribute in the theme config such as `currentUserAttr`. That will be a little tricky to implement, though, because right now all themes must provide all attributes (or else they're considered broken and will cause `matterhorn` to abort). This behavior is to protect from developer mistakes where an attribute was documented but not provided by all built-in themes. The issue will become that once `currentUserAttr` is documented (and it should be), all themes must provide it to avoid this problem. But that won't be possible, because it can't be known in advance before the user signs in! That will require the theme-checking machinery to change a bit to allow for this case, such as by adding support for a dynamic attribute whitelist with `currentUserAttr` as its only entry initially.

I'd also like to state another assumption for how this should behave for us to agree on: if the user's theme configuration does not specify the current user attribute *or* provides a style only, then the default behavior should be the current behavior, i.e., the current user's username is hashed to deterministically choose a color. (If the theme config provides a style, then the style would be applied to the chosen color attribute.) This should basically be automatic with the current theming machinery.

**Comment by jtdaugherty** [comment]
This is from a conversation with @wiruzx elsewhere, but I want to capture it here for the record.

To summarize my thinking on how this could work:
* To be consistent with how all other attributes and styles are specified, the theme would be the best place to provide an attribute and/or style to format the current user's username.
* By default, the current user's username should be formatted as it currently is, by username hashing to choose a color.
* If the user specifies a special theme attribute in their theme config, e.g. `current-user`, then that should override the hashing behavior.
* However, the theming machinery cannot support what I've described above right now, because it does not allow any theme attribute to be optional. All themes must provide all attributes (which is deliberate). This is enforced by `Themes.validateInternalTheme`.
* To support what I've described, the theme machinery will need to be modified so that some attributes are permitted to be left out of themes as long as they have a fallback behavior. For that, it could be as simple as a whitelist in Themes, `themeOptionlAttrs :: [AttrName]`, and then `validateInternalTheme` would need to be updated to allow attribute names in that list to be left out of themes.

If all that gets done, that would make it possible for the current username attr name to be omitted from the theme. Then there needs to be another change to make it so that the current user's name rendering looks up the current username attribute name in the active theme and uses it if it's present, or falls back to the computed attribute (the current behavior).

**Comment by wiruzx** [comment]
After a discussion with @jtdaugherty, we decided that it'd be better if he continues work on this issue.

**Comment by jtdaugherty** [comment]
This is now implemented in `feature/current-user-color` via 2a7aaaf0fb6edb7f17d52d04e41766bef48d5b6b for those who want to try it out.

**Comment by jtdaugherty** [comment]
This has been merged to `develop`.
