### ISSUE TITLE
toggle-channel-list-visibility remap in config.ini not work

### ISSUE THREAD

**Issue by fey** [matterhorn-chat/matterhorn#517]
Hello, toggling channel list by F2 not working for me, so i want to remap or use some command a la `/toggle-channel-list`

In `~/.config/matterhorn/config.ini` i put following
```ini
[KEYBINDINGS]
toggle-channel-list-visibility = C-h
```
But its not working

PS i use `xfce4-terminal 0.8.7.4`

**Comment by jtdaugherty** [comment]
Thanks for the report!

That particular binding won't be possible, unfortunately, because of how input in terminals works:

https://unix.stackexchange.com/questions/327953/make-ctrl-backspace-different-than-ctrl-h

> The basic problem is that a terminal emulator (or a terminal console) aims to emulate an actual terminal, usually a VT220 or a VT100. In the olden days when VT terminals ruled, characters above 127 were considered exotic. Characters 0 to 127 are divided into 95 printable characters (33 to 126) and 33 control characters (0 to 31, that is Ctrl-@, Ctrl-A, Ctrl-B, Ctrl-C ... Ctrl-H aka BS, Ctrl-I aka Tab ... Ctrl-J aka LF ... Ctrl-M aka CR ... Ctrl-Z, Ctrl-[ aka Esc, Ctrl-\, Ctrl-^, Ctrl-], and 127, Ctrl-?, aka Del). That's why key Escape is the same as Ctrl-[, Tab as Ctrl-I, and Enter as Ctrl-M.

Notice, for example, that if you enter some text in `bash` and press `C-h`, it will behave as `Backspace` does there, too, because they are the same key as far as the terminal is concerned. The same goes for `C-[`/`Esc`, `C-I`/`Tab`, etc., as mentioned in the quoted comment above. I hope that helps!

**Comment by fey** [comment]
Thanks! I mapped to `M-h`

**Comment by jtdaugherty** [comment]
Great!
