### ISSUE TITLE
kwallet integration not working ( by desigm? )

### ISSUE THREAD

**Issue by EugenMayer** [matterhorn-chat/matterhorn#539]
I do not think matterhorn can do anything about that, i guess this is rather kwallet related, but most probably the docs need some updates so people do not waste their time.

It seems like `secret-tool` cannot integrate with kwallet, it seems not even implemented. It is this error https://github.com/Foundry376/Mailspring/issues/681

Installing gnome-keyring fixes that, but of course the password is then stored in the gnome-keyring.

Suggestion is, we adjust the docs to tell that kwallet is yet not supported ( broken ) and link to an issue, so people do not try it.

**Comment by jtdaugherty** [comment]
Thanks for the report!

The lack of support for KWallet is not deliberate. The requirement for `secret-tool` is just this: it should output a password on stdout. Based on my google searches, `kwalletcli` can indeed do that, assuming it is properly configured.

Since the behavior you described seems to be more about KWallet configuration, I don't think it belongs in the Matterhorn documentation. Judging by [the man page for kwalletcli](https://www.systutorials.com/docs/linux/man/1-kwalletcli/), there are some requirements for running it:
```
It will only work if KDE is running (DCOP) and reachable (via X11).
```
That will be a matter of the environment, at the very least, via the `DISPLAY` variable and perhaps others.
