### ISSUE TITLE
Space for Keybinding

### ISSUE THREAD

**Issue by misery** [matterhorn-chat/matterhorn#558]
I like to use ```enter-fast-select``` with ```C-Space``` but it seems ```Space``` is not recognized as key. Please add support for it.

**Comment by jtdaugherty** [comment]
The `C-Space` binding may not be working for a variety of reasons unrelated to Matterhorn, such as interference by your window manager or terminal emulator environment. In addition, it's worth pointing out that `Ctrl` combined with many keys will not give the desired behavior due to the vagaries of terminal emulator implementation, so when choosing keybindings you may need to find alternatives to your preferred bindings. That is usually not a Matterhorn issue because Matterhorn doesn't control how the terminal translates keypresses into byte sequences. `C-Space` in particular seems to be a troublesome one for many environments.

https://unix.stackexchange.com/questions/116239/ctrl-space-not-getting-through-ssh
https://github.com/microsoft/terminal/issues/2865
