### ISSUE TITLE
Fullname for enter-fast-select

### ISSUE THREAD

**Issue by misery** [matterhorn-chat/matterhorn#559]
I like to request that ```enter-fast-select``` could search in fullname and acronym. The user with name "Erika Mustermann" with acronym "EM" with username "mustermann" can only be select by "mustermann". But I remember my colleague by first name or acronym. As mattermost server provides both it would be nice if the fast selector could search into that data, too.

**Comment by jtdaugherty** [comment]
Thanks for the report!

Right now, Matterhorn only supports username and "nickname" rendering and matching for users. For full name matching, that will be included in #420 when it is implemented. I'll close this and add a comment to #420 about the acronym matching feature since it can only be supported when full name rendering is enabled.
