### ISSUE TITLE
Improve help screen

### ISSUE THREAD

**Issue by MartinDelille** [matterhorn-chat/matterhorn#564]
After launching `matterhorn`, I wonder how to switch channel with the keyboard and type the `/help` command to access this screen:

<img width="1010" alt="Screenshot 2020-02-17 10 38 40" src="https://user-images.githubusercontent.com/879889/74641501-b4852380-5171-11ea-8ba2-94ac117a64b9.png">

Here are a few suggestion to improve it:

- Don't write with white on light blue (not very readable)
- Allow vim key like navigation (j / k for up/down)

**Comment by jtdaugherty** [comment]
The first bullet you mentioned above is now fixed in `develop`. The second bullet is not possible to address right now, unfortunately. "j" and "k" are already bound to other key events that would conflict with the keyboard events that manage scrolling, and our key event system is not capable of mode-specific overrides right now. Thanks for your suggestions!
