### ISSUE TITLE
syntax / emoji / script paths

### ISSUE THREAD

**Issue by kerhac** [matterhorn-chat/matterhorn#584]
Thanks for the great client!
I noticed the lookup for the syntax files are hardcoded to `xdg getUserConfigDir`. To allow putting the syntax file to `/usr/share/matterhorn/syntax` it would make more sense to use `xdg getAllDataDirs` instead. Same thing applies for the emojis and scripts location.

This would then allowing installing the files at those location using system package.

**Comment by jtdaugherty** [comment]
@kerhac thanks for the suggestion!

We could add the data directories to the search path, but we can't use *only* `getAllDataDirs` because that would break the current behavior; `getUserConfigDir` isn't included in `getAllDataDirs`. Still, we can investigate what it would take to support multiple possible paths for those files.

**Comment by jtdaugherty** [comment]
This is now fixed on `develop`. Now, if no syntax XML paths are specified in the config file, the list of searched paths now includes the XDG data directory list (at the end of the search path list). The list now includes the user's XDG configuration directory, the build source code directory, the Cabal data directory for the package, and the XDG system data directories.
