### ISSUE TITLE
Improvement to/configurable M-a sorting

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#593]
M-a is an awesome feature, but it would be even better, IMO if the sorting was improved and/or configurable.  Specifically, I would prefer if M-a took me to chats in something like the following order (with LIFO order within each):

 * Private messages
 * Private message groups
 * Explicit mentions in public channels
 * Implicit mentions (e.g. @everyone) in public channels

**Comment by jtdaugherty** [comment]
Right now we already have something that is close to what you want: the `focus-next-unread-user-or-channel` keybinding event, which is like `focus-next-unread` (default `M-a`) but prefers private (DM) message channels before selecting other channels. You can bind a key to that to get that behavior; it has no binding by default. To do that, put this in your `config.ini`:
```
[keybindings]
focus-next-unread = unbound
focus-next-unread-user-or-channel = M-a
```
I'd like to know whether that will work well enough for you. I am not excited about making the behavior more configurable than it already is, since that has its drawbacks. I'd rather keep the behavior as it is (simple but predictable).

**Comment by jtdaugherty** [comment]
(Also relevant to this ticket is my fix for https://github.com/matterhorn-chat/matterhorn/issues/596 that I just pushed earlier today; the event I mentioned above wasn't discoverable due to a problem with how our help text and documentation were generated, but as of now, that is fixed.)

**Comment by jtroup** [comment]
Thanks, this is good enough for me.  Feel free to close the issue.

**Comment by jtdaugherty** [comment]
Okay, thank you!
