### ISSUE TITLE
"Improve" key bindings in channel select mode

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#609]
Whenever I go into fast channel select mode (C-g), after typing a few letters to narrow down, I then try to go up or down in the list of channel options and am surprised when up/down arrow moves the cursor to the beginning or end of the line.  I realise C-n/C-p do what I want and both a) are readline-idiomatic, and b) work in normal edit mode, but I would argue that most people tend to use Up/Down before C-n/C-p and also I don't think I remember seeing Up/Down mean move-to-start/end-of-line anywhere else (even in Matterhorn)?

**Comment by jtdaugherty** [comment]
The arrow keys have that behavior because of how the text editors in Matterhorn work: in general, arrow keys move up and down lines (in a multi-line setting). When the cursor is on the first row, Up moves to the beginning of the line, and when the cursor is on the last line, it moves to the end of the last line.

With that said, the arrow keys do *not* behave that way in single-line editing mode since instead they control history navigation. But in the channel selection mode that you mention, the default behavior kicks in.

For what it's worth, I don't find arguments based on what "most people" are likely to want to be very compelling. But knowing that this doesn't work for you *is* helpful!

I'm happy to investigate adding additional keyboard events with Up/Down bindings to the channel selection mode as alternative ways to trigger the `C-n`/`C-p` behavior.

**Comment by jtdaugherty** [comment]
As of 89d9eee69a6b92a521b6f6b91e4bed886923f327 this is now fixed:

* `Up` and `Down` are available as alternatives to the `C-p` and `C-n` keys, respectively, and
* The behavior of these additional keys can be customized with the new keyboard event names listed in the commit message.
