### ISSUE TITLE
Mouse support

### ISSUE THREAD

**Issue by 3v1n0** [matterhorn-chat/matterhorn#616]
Even in CLI, having mouse support may be useful for scrolling for example (especially when you've a trackpoint :smile:)... 

So, would be nice to be able to toggle mouse selection and scrolling, while keeping the keybinding interaction intact (as weechat or vim allows)

**Comment by jtdaugherty** [comment]
That would indeed be nice, but I'm sorry to report that we cannot support it.

**Comment by giann** [comment]
Any reason why?

**Comment by jtdaugherty** [comment]
Yes, there are definitely reasons, although I am afraid it may not be useful to go into the details here since they will only be meaningful to people who have experience with the libraries we're using for terminal I/O.

**Comment by giann** [comment]
Github is not the place to discuss technical details?
Also why would you assume ignorance on my part? Even if I don't know that library in particular, I could inform myself. Others who have the experience you speak of could come about this issue and decide to help.

**Comment by jtdaugherty** [comment]
@giann I appreciate your concern and I realize my response may have been a bit frustrating. I will elaborate, but please bear in mind that my comments aren't really about assuming ignorance on *your* part in particular. Ordinarily I completely agree with you that sharing the details would help a future contributor. I'll comment more on that below.

The libraries that Matterhorn uses for terminal I/O (`vty` and `brick`) *do* support rudimentary mouse input using terminal mouse input byte sequences. I say rudimentary because they support detecting mouse clicks at particular screen coordinates. But in order to translate that into something useful in Matterhorn, those coordinates need to be mapped to particular UI elements. The `brick` library provides some help with that; it allows us to associate UI elements with "resource names" that can then be mapped to mouse events when they arrive. There are two technical reasons why even that isn't enough: first, to support arbitrary mouse interaction with Matterhorn UI elements, every UI element must be equipped with a resource name and a mouse event handler must be written for each one. Second, for performance reasons, the Matterhorn UI's rendering process uses a great deal of render caching, and render caching essentially breaks the mouse input event coordinate resolution process.

Another thing I need to point out is that this ticket was about *mouse selection*, which is even harder to implement than merely *mouse clicking*. Mouse scrolling is usually trivial and doesn't require any additional work because mouse scroll events are usually just page up / page down or up / down events, which Matterhorn already supports.

Lastly, if the underlying concern of this request was to make it possible to copy messages to the clipboard (i.e. via selection) then Matterhorn already offers that feature without mouse interaction (`C-s`; `Y`).

I haven't elaborated on this before for a number of reasons:
* End user desire for this feature seems to be very low in terms of number of users interested.
* Even if user interest increased, the amount of work to support this is high even if it can be made to work, and I have concerns that it can't.
* I am not motivated to accept patches to add this feature because I think it is a rabbit hole feature that is out of place in a terminal application. Adding features that require added complexity and maintenance burden that users are not likely to use is something I like to avoid, and this is a feature that would have a pretty fundamental impact on how Matterhorn is designed. I don't see that as a worthwhile trade-off to make.
