### ISSUE TITLE
Some terminal keybindings don't work

### ISSUE THREAD

**Issue by 3v1n0** [matterhorn-chat/matterhorn#621]
As promised in issue #617 editor keybindings are now editable (thanks!), however it looks like there's a problem with some of them.

My configuration is:

```ini
[KEYBINDINGS]
page-up = PgUp, M-u
page-down = PgDown, M-n
enter-fast-select = C-g, C-p, C-k
focus-prev-channel = C-PgUp
focus-next-channel = C-PgDown
focus-last-channel = M-.
scroll-up = Up, M-K
scroll-down = Down, M-J
invoke-editor = C-M-e
select-up = k, Up, M-k
select-down = j, Down, M-j
toggle-multiline = M-e, C-Enter, M-Enter ; C-Enter doesn't work

editor-prev-char = Left, M-h
editor-next-char = Right, M-l ; M-l works only after remapping `clear-unread`, no error though
editor-prev-word = C-Left, M-b
editor-next-word = C-Right, M-w, M-e
editor-delete-next-word = C-Del, M-Del ; M-Del doesn't work!
editor-delete-prev-word = C-w, M-Backspace, C-Backspace ; C-Backspace doesn't work!
editor-yank = M-y, C-y

quit = C-q, C-d
```

~~So just setting `editor-delete-char = Backspace` (which should be default) breaks the functionality, while some other keybindings (that I've commented above) aren't working yet.~~

**Comment by jtdaugherty** [comment]
In general, terminals don't support some modifier/key combinations because of how input is encoded. So some key combinations like `C-Enter` just will not work. And we can't always know when they won't work, because it can depend on the terminal emulator, the value of `TERM`, etc. I would not be surprised if `C-Delete` and `C-Backspace` fail to work for the same reason, and that also goes for some `M-` combinations. It's also possible they should work but don't because of Matterhorn's terminal input processing library; so if you find that some key combos do work for other applications but not for Matterhorn, we could investigate those specific combos.

It would also help me if you could be more specific about what you mean by "doesn't work" and the comment you made about `editor-next-char`.

Lastly, we aren't in agreement about a default of `editor-delete-char = Backspace`, since that is fundamentally backwards; that event causes the deletion of the character under the cursor, not the one before it. But the nice thing is at least in theory that we don't have to agree. That's why we added custom keybinding support. 😊

**Comment by 3v1n0** [comment]
So, I know that terminals can be quite complicated for this, and they don't respect what we want all the times, but I'm speaking of a scenario (ubuntu 20.04, gnome-terminal) where such combinations work properly with vim, ksh, bash (readline really).

So, something that my $TERM does support (a part from `C-Enter` I think).

> I would not be surprised if `C-Del` and `C-Backspace` fail to work

So, here `C-Del` works properly in matterhorn, while `M-Del` and `C-Backspace` fail.

For reference you can test this in any readline program (adding `"\C-h": backward-kill-word` to your `~/.inputrc`) in zsh with `bindkey "\C-h" backward-kill-word` (I've something similar for weechat too).

While by "fails" in the comments I meant that there's no effect, for `M-Del` it's different as I do have output but not the one expected:

```
> foo bar [3;3~baz
```

So a `[3;3~` literal (its keycode) is printed all the times that I do M-Del.

> It would also help me if you could be more specific about what you mean by "doesn't work" and the comment you made about editor-next-char.

So... By "doesn't work" I meant that it has no effect at all, this is true for all the underlined cases, but `M-Del` as explained above.

> Lastly, we aren't in agreement about a default of editor-delete-char = Backspace

As per `editor-delete-char` you're right, and I actually I confused it, so you're correct.
I did put in there as I wanted to test the Backspace code as I didn't got it working and wanted to try to override the default. But it does what it's expected to do.

**Comment by jtdaugherty** [comment]
> For reference you can test this in any readline program (adding "\C-h": backward-kill-word and "\e[3;5~": kill-word to your ~/.inputrc) in zsh with bindkey "\C-h" backward-kill-word (I've something similar for weechat too).

Unfortunately neither of those changes worked for me. I'm running iTerm2 on macOS. With or without those changes, my terminal got only a Backspace key whenever I pressed Ctrl+Backspace.

> So, here C-Del works properly in matterhorn, while M-Del and C-Backspace fail.

And for me, `C-Del` does not work, while `M-Del` does. Apparently `C-Backspace` behavior depends on whether the terminal is configured to send a sequence or not. It would seem that for iTerm2, only Backspace is sent. I could configure iTerm2 to send a custom sequence, but the challenge for `matterhorn` is: is there a standard sequence? If so, where is that documented?

**Comment by jtdaugherty** [comment]
Also, since I meant to ask: have you tried these bindings on other terminal emulators on your system?

**Comment by 3v1n0** [comment]
> Also, since I meant to ask: have you tried these bindings on other terminal emulators on your system?

Well, I've been running them successfully in both xterm, gnome-terminal and Tilix for years.

So, maybe you want to try them in a linux VM?

**Comment by jtdaugherty** [comment]
My question is whether you have tried the failing bindings with `matterhorn` in other terminal emulators on your system.

**Comment by 3v1n0** [comment]
So... In `xchat` all the `Alt+stuff` keybindings don't work, neither in matterhorn and in other apps (zsh, bash...), not because they're not caught but because they've a different binding it seems.

As per the others (just `C-Backspace` is left at the end), they work in zsh/bash but they still don't work in matterhorn.

gnome-terminal, and Tilix have just the same behaviors.

**Comment by jtdaugherty** [comment]
> So... In xchat all the Alt+stuff keybindings don't work, neither in matterhorn and in other apps (zsh, bash...), not because they're not caught but because they've a different binding it seems.

My question is whether they work when they are set up to be the expected binding. So in other words, if `M-Del` isn't doing what you expect in `matterhorn`, then if you set up `xchat` to expect `M-Del` to trigger some behavior, does it actually trigger that behavior? In other words, what we are testing is whether your terminal is able to send a recognizable sequence for that key combination that some application can correctly interpret.

> gnome-terminal, and Tilix have just the same behaviors.

Would it be possible for you to test in other terminal emulators, such as `xterm`, `rxvt`, or `konsole`?

**Comment by 3v1n0** [comment]
I don't know why I mentioned `xchat` while I wanted to say `xterm`... Sorry I'm burned :-D.

As per `rxvt`, supports all the keybindings in zsh/bash but matterhorn has the same behavior that it has with Tilix and gnome-shell (last two based on same backend btw) - So works with zsh, not with matterhorn.

Didn't try konsole, but I imagine will behave the same.

**Comment by jtdaugherty** [comment]
I have a fix for your `C-Backspace` case, and you may be able to repeat the procedure for other bindings. Here is the fix for `C-Backspace`:
1) Create a file `~/.vty/config` and add to it the line `map _ "\ESC[3;5~" KBS [MCtrl]`. This configuration file is loaded by the `vty` library, the library that Matterhorn uses to process terminal input and produce key events for Matterhorn. This configuration line tells `vty` to translate the input sequence `\ESC[3;5~` to the `KBS` (backspace) key with the modifier list `[MCtrl]` (control).
2) Set up the desired event in `~/.config/matterhorn/config`'s `[keybindings]` section to be triggered by `C-Backspace`.

That procedure will work as long as you know the escape sequence for your key combination and can add additional `map` lines to `~/.vty/config`. I'm also going to put these steps in the README's FAQ. Please let me know if this addresses your `C-Backspace` behavior.

**Comment by jtdaugherty** [comment]
This is now documented [in the project README](https://github.com/matterhorn-chat/matterhorn/tree/develop#why-doesnt-matterhorn-support-my-desired-keybindings).

**Comment by 3v1n0** [comment]
Soooo.... Thanks for the hint!

This indeed worked straight-forward for the said `M-Del` once I added:

```
map _ "\ESC[3;3~" KDel [MMeta]
```

However, for `C-Backspace` here was a bit more complicated, so I ran matterhorn with `VTY_DEBUG_LOG=/tmp/matterhorn-keys-debug` and I got this: https://paste.ubuntu.com/p/mnxqDh4yZq/

As you can see it contains:

```
input bytes: "\b"
dropping input bytes
```

As per this, I included `map _ "\b" KBS [MCtrl]` into my vty config and it all worked well! :-)

So, thanks a lot, maybe you want to close this bug now, as hacking vty config seems possible to get all the possible missing pieces.

Maybe you can mention in the README that to get the actual keys one can just run with the debug logging enabled (and see what happens real-time by `tail -f` that file, while typing in matterhorn`.

PS: The README.md's link to https://hackage.haskell.org/package/vty-5.28.2/docs/Graphics-Vty-Input.html has syntax error.
PS2: All the terminals will show you the combo by just doing `C-v` followed by the key combination.

**Comment by jtdaugherty** [comment]
I'm glad you got it working! And thanks, I will also mention Vty debug logging and fix the syntax error.
