### ISSUE TITLE
#☕ channel name causes overflow of channel list into message buffer

### ISSUE THREAD

**Issue by julian-klode** [matterhorn-chat/matterhorn#625]
We have a channel called #☕ - It seems that #☕ is only recognized as one character instead of 2, and hence the entry in the channel list is one character too long causing it to shift the | and the messages one character to the right compared to above/below it. Same for other unicode characters I guess.

**Comment by jtdaugherty** [comment]
That's unfortunate, but yes,  you're right - it's due to the fact that a multi-column emoji character is being used. Matterhorn's support for multi-column Unicode characters is spotty, largely due to the nature of poor support for Unicode characters in terminals in general. We mention this in [the README](https://github.com/matterhorn-chat/matterhorn#does-matterhorn-support-graphical-emoji), but I'm afraid the details pertaining to this problem are too numerous to summarize easily here. For more information you could check out the tickets I've linked below, but in the mean time Matterhorn's support for Unicode characters will vary by terminal emulator and by character.

* https://github.com/jtdaugherty/vty/issues/175
* https://github.com/matterhorn-chat/matterhorn/issues/569
* https://github.com/matterhorn-chat/matterhorn/issues/389

**Comment by jtdaugherty** [comment]
It's also worth mentioning that there is a potential way to ease your pain if you are comfortable building Haskell packages. The `vty` package provides a tool `vty-build-width-table` that will interrogate your terminal to gather Unicode character width data and Matterhorn is able to load the resulting width map on startup (if you're running one of the more recent versions). That feature is not documented in Matterhorn yet (see #569) but it may help you in this case. If you want to pursue that, please reopen this and I can provide help.
