### ISSUE TITLE
Cannot `/leave` direct messages

### ISSUE THREAD

**Issue by dpb1** [matterhorn-chat/matterhorn#626]
When I try to `/leave` a DM from matterhorn, I get:

```
The /leave command cannot be used with this channel. 
```

This same command does work in the web UI, and does as you would expect (simply removes the channel from the list of DMs until the person talks to you again)

**Comment by jtdaugherty** [comment]
For now, for DM channels, the right command to use is `/hide`.

**Comment by jtdaugherty** [comment]
For posterity, I decided not to support `/leave` for this purpose since I believe that it doesn't have quite the right meaning for DM channels. They can never truly be left, and they reappear in the channel list when the other user messages you, so both of those facts make "leaving" seem like the wrong notion to me. However, I realize none of that matters because the web client has a different behavior and Matterhorn's behavior may seem surprising.

Would it be helpful to have the error message at least say to use `/hide` instead? I personally dislike error messages that tell me to do a thing that the computer could have done just as easily, so I'm torn.

**Comment by jtdaugherty** [comment]
On thinking about this more and talking with some other folks, I'm going to investigate making `/leave` do what `/hide` does for group and single-user DM channels.

**Comment by dpb1** [comment]
Thanks for asking @jtdaugherty 

From a user perspective, I was unaware of how the server handles me leaving a DM. The only UX I really wanted was the channel off my list.  From that perspective, `/hide` makes much more sense, since I cannot really leave a DM.

Printing out a message would be an improvement for me as a user (would have stopped me from filing this bug), but it the computer would JDTRT, I would have been even better with it.

Then, I think the only thing to add would be in the help a bit of text on '/leave' mentioning '... or hide the current DM or group'.

**Comment by jtdaugherty** [comment]
The `/leave` command now hides DM and group channels on the `develop` branch and will go out in the next release. Thanks!
