### ISSUE TITLE
Support plugin-driven user input dialog boxes

### ISSUE THREAD

**Issue by dpb1** [matterhorn-chat/matterhorn#630]
## What happened

The [remind plugin](https://github.com/scottleedavis/mattermost-plugin-remind) is an example, it uses a dialogue to display output, I'll attach some screenshots to show behavior.  The reliance of this plugin on the dialogue functionality combined with #476 actually makes it appear that this plugin just doesn't work.  It actually does work reasonably well, you just can't see output.

## What I would expect

Base functionality: just display the text that is in the dialogue, with maybe a 'reduced functionality' warning.
Advanced Functionality: Fully support the dialogue, with the actions that are presented (Cancel, acknowledge, list, etc)

## Screenshots

When running the command listed, you get blank output in Matterhorn:

![remind-me-terminal](https://user-images.githubusercontent.com/1417497/85894612-52d56580-b7b2-11ea-8222-93eb758f0074.png)
![remind-list-terminal](https://user-images.githubusercontent.com/1417497/85894620-5668ec80-b7b2-11ea-9864-8dac946f9faf.png)

Some interaction examples in the web-client:

![remind-me-web-client](https://user-images.githubusercontent.com/1417497/85894674-726c8e00-b7b2-11ea-9926-043ba6dd04a6.png)
![remind-list-web-client](https://user-images.githubusercontent.com/1417497/85894677-74365180-b7b2-11ea-844c-bc6287552834.png)

This is what happens when you click on 'View Completed Reminders' (for example):

![remind-list-click-view-all](https://user-images.githubusercontent.com/1417497/85894682-76001500-b7b2-11ea-919b-1be0d72a9543.png)

**Comment by jtdaugherty** [comment]
Thanks for filing this!

**Comment by jtdaugherty** [comment]
Interestingly, it looks like the web client embeds the user input form in the message area. The mattermost server docs make it look like a modal / pop-up window. Perhaps both are possible.

**Comment by jtdaugherty** [comment]
For reference:
* https://docs.mattermost.com/developer/interactive-messages.html
* https://docs.mattermost.com/developer/interactive-dialogs.html

**Comment by lukasjuhrich** [comment]
So what needs to be done to implement this?
Is there anything I can do / any info I can provide to assist (payload)?

---
_(note to future self: relevant parsing section is here: https://github.com/matterhorn-chat/matterhorn/blob/b22da99da132e29d7f92ab42c2d05c03fbd9a321/src/Matterhorn/Draw/Messages.hs#L406-L412)_

**Comment by jtdaugherty** [comment]
@lukasjuhrich Before implementation on this can begin, some research needs to be done. We haven't looked into the range of possible UI elements that are involved with supporting this feature, and some of them could be impossible to support in a terminal (if they depend heavily on mouse or scroll wheel interaction, for example). But if we can muster a reasonable terminal UI equivalent for whatever the official clients support, then we could consider supporting this feature.

A note about mouse support, while I'm on the topic: as you might already know, Matterhorn does support mouse input. But we consider it optional and we'd prefer to design the client so that someone can use Matterhorn fully without ever enabling mouse interactions. If supporting this feature requires us to reconsider that position, that's something we'll need to know.

If you're interested in helping, that research would be a necessary first step. Otherwise I'll probably be the one to get to this at some point but right now I can't provide an estimate as to when.

**Comment by lukasjuhrich** [comment]
May I suggest solving an easier problem first? Namely, displaying as much meaningful content as possible without necessarily implementing ineractivity. I would be perfectly fine with either not displaying actions at all or a `[2 actions]` placeholder if I could at least see the text that e.g. `/remind list` returns. Feels like an improvement over an empty message in any way.

In hopes this is helpful: I've looked at the websocket event `/remind list` initiates, and we get an ephemeral message as dumped here: https://git.agdsn.de/-/snippets/117

…we see that 
- `message` is empty, but the `attachments` hold the actual content.
- In each attachment, `text` holds the relevant message
- In each attachment, the UI elements are represented in the `actions` field
- Buttons are `type: button`
- A dropdown action has `type: select`, a `name`, and  `options: [{text: "A", value: "a"} …]`

**Comment by jtdaugherty** [comment]
Thank you for that information, @lukasjuhrich!

As for your suggestion, I view that as a temporary coping strategy rather than a solution. I'd be okay with someone implementing that as long as the UI indicated that a graphical client would be needed to interact with the actions (in this example). I'd also be concerned about that accidentally becoming our only long-term approach to dealing with this feature if we don't have a commitment to investigating what else we could do, so in a way I'd see that as being worse than doing nothing. So either way, I'd like to get closure on this by investigating the features we'd need to support even if a temporary behavior is implemented.

**Comment by jtdaugherty** [comment]
Relevant to #770:

https://github.com/blindsidenetworks/mattermost-plugin-bigbluebutton/blob/master/server/plugin.go

**Comment by jtdaugherty** [comment]
Due to extremely limited time on my part, I'm going to close this as something I am not going to be able to prioritize. If this needs to be prioritized in the future, let's re-open it or create a new ticket.
