### ISSUE TITLE
/gifs in a DM on another client, appears in current channel on Matterhorn

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#634]
If I use the Mattermost IOS client, go to a DM and use the /gifs command, then on Matterhorn the GIF line(s) (i.e. "/gif test \n  [image:GIF for ' test']") appear both in the correct DM channel/window, but also whatever channel I had open in Matterhorn at the time.

 * This only applies to gifs I send, not gifs I receive
 * This is with Matterhorn 50200.9.0 and Mattermost Enterprise Edition 5.23.1
 * This misplaced GIF line only appears in Matterhorn; if I rerun the experiment with IOS client + Web UI, it doesn't appear misplaced in the web UI.

**Comment by jtdaugherty** [comment]
What is `/gifs`? It isn't a valid command on my mattermost server.

**Comment by jtroup** [comment]
Apologies, I didn't realise it was a plugin.  It's from:

  https://github.com/moussetc/mattermost-plugin-giphy/

**Comment by jtdaugherty** [comment]
Thanks, that helps. I took a look. I think the reason you're seeing the behavior that you described is that the plugin sends *server informative messages* and those messages always get displayed in the current channel you're in. They also get sent to all clients connected on the same account, apparently, which is why Matterhorn gets them and why it also shows them in the current channel. Since that's a server feature, we don't have control over it.

Also, the plugin you are using uses [interactive messages](https://docs.mattermost.com/developer/interactive-messages.html) which Matterhorn does not support. For a bit more information, see [this ticket](https://github.com/matterhorn-chat/matterhorn/issues/630).
