### ISSUE TITLE
Please include OS error that's preventing a reconnect

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#635]
Hello, this morning I find that I'm no longer connected to the company's mattermost server, but I don't know why I'm not connected.

In the upper right-hand corner, there's a red `NOT CONNECTED` in a shiny box, and in the channels, there's some text:

```
[15:50:01] Disconnected. Will refresh when connected.
[17:37:12] Cannot send messages while disconnected.
[17:37:12] Disconnected. Will refresh when connected.
```

but there's no indication of why I'm disconnected: is the server dead? is the socket dead? can I route packets to the server? what OS-level error is preventing it from reconnecting?

Thanks

**Comment by jtdaugherty** [comment]
@kquick to address this I wrote up a patch to propagate the exception that triggered the disconnection through to the logic that adds these "could not send messages" messages to the user. While those exceptions will contain lower-level details like the ones @setharnold is asking for, they are not in a human-friendly format (due to them being generated ultimately by the `Show` instance for the exception, which is unfortunately what we get by default for most exception types if we use `Control.Exception.displayException`).

I'm not a fan of presenting raw `Show` values to the user, but at the same time, I can see the value of providing some lower-level details about the error to the user beyond just "not connected." Thoughts?

**Comment by jtdaugherty** [comment]
(Patch: 2b3cdc42b7e33a1a58dd8aafd313b1eee27e4c57)

**Comment by jtdaugherty** [comment]
@setharnold also, in case it helps, for the time being it is also possible to find out about the connection status issue by running `/log-snapshot` around the time that the disconnection occurs to get a log file with more details.

**Comment by setharnold** [comment]
Oh cool, thanks! I've got two good candidates for my most recent error, and I'm not sure which one was the motivating factor: one, the snap packaging refreshed and that breaks all kinds of things, two, our VPN seemed unhappy, another long-lived connection for IMAPS didn't gracefully reconnect either.

Restarting both the VPN and matterhorn was enough.

**Comment by jtdaugherty** [comment]
Okay, great. Both of those are likely to be reported in somewhat generic terms by Matterhorn even with the patch I linked above. That is important to point out since there is a limit to how much information the low-level network errors will contain about the cause of the problem. Still, I realize any information is probably more useful than no information.

**Comment by jtdaugherty** [comment]
It's also worth pointing out that Matterhorn attempts to reconnect on a continuous basis, so once the network is healthy again, Matterhorn will reconnect. And if you want to trigger a reconnection attempt manually, you can use `/reconnect`.

**Comment by kquick** [comment]
I have a small concern that the exception might contain sensitive information (e.g. show the attempted request in the exception, where the request might contain credentials or be a retry from a private channel).  This  is a small concern because I don't think this is a likely situation, but it bears thinking about.  Another alternative would be to ensure that the exception information would appear in any generated log files and then update the message to say "Cannot send messages while disconnected; use /log-snapshot to obtain details.  Automatically reconnection attempts are in progress."  That way the UI doesn't show relatively ugly `Show` output and the user is more in control of the output in case there is sensitive data.

**Comment by jtdaugherty** [comment]
@kquick that sounds like a nice compromise. @setharnold would that approach of recommending `/log-snapshot` been adequate for you?

**Comment by setharnold** [comment]
On Tue, Jul 07, 2020 at 10:26:20AM -0700, Jonathan Daugherty wrote:
> @kquick that sounds like a nice compromise. @setharnold would that
> approach of recommending `/log-snapshot` been adequate for you?

It probably would have been very helpful to see a reference to
/log-snapshot at the time, yes.

I haven't yet seen the full "show" rendering of a connection exception, so
I'm not too sure about the details of logging the exception to a file
rather than showing it on screen.

My inclination is to avoid logging anything that might be credentials or
privileged, and prefer to display that information on screen only, but a
user requesting a log is different than the application just always
maintaining the log, so maybe my concern is misplaced.

Thanks

**Comment by kquick** [comment]
I think some more background on the logging would help for context. Does the "Purpose and Context" at the start of
**https://github.com/matterhorn-chat/matterhorn/wiki/Logging** address your concerns, @setharnold ?

**Comment by setharnold** [comment]
On Tue, Jul 07, 2020 at 05:31:28PM -0700, Kevin Quick wrote:
> I think some more background on the logging would help for context. Does
> the "Purpose and Context" at the start of
> **https://github.com/matterhorn-chat/matterhorn/wiki/Logging** address
> your concerns, @setharnold ?

I really like this part:

> Matterhorn generally does not log information that is known to be sensitive (e.g. passwords),

Mistakes happen, it's easy to overlook new exceptions etc, but at least
this is a promising position. :)

Thanks

**Comment by jtdaugherty** [comment]
The error message we display in this situation is now improved on `develop`. Thanks, everyone!

**Comment by setharnold** [comment]
Yay, thanks!
