### ISSUE TITLE
tab completion is unpredictable

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#644]
Hello, several times now I've been moments away from accidentally using `@all` or summoning the CEO due to `<tab>`-completion oddities.

For example, I'll type `@joe<tab>` (trying to complete `@joemcmanus`) and `@all` will be completed in its place. (This has happened twice.)

Another instance is typing `@sb<tab>` (trying to complete `@sbeattie`) and `@sabdfl` will be completed in its place.

I also would prefer if people not in the channel are not completed, or at the very least, given less preference in completion to people who are in the channel. (Not completing people who aren't in the channel would make more sense when compared with eg `irssi` or `weechat`, etc., but may or may not make sense in the slackalike world. I certainly find it confusing that people I've never interacted with are having their nicknames completed rather than people I share a channel with.)

Thanks

**Comment by kquick** [comment]
Regarding your latter comment, users in the channel are listed in order before users not in the channel, and users not in the channel are prefixed with a `*` character as well as a message in the auto-completion box.

**Comment by jtdaugherty** [comment]
It's possible this is due to high latency, although without being able to see it in person I can't say for sure. If the response for completions comes back slowly enough, it might be possible for the always-available `@all` and `@channel` alternatives to be in the list before the other entries come back from the server. I'd have to look into the logic, though.

As for the other requests, we definitely don't want to complete only users in the channel. While I can see that it makes sense for you, in the general case it is important to complete users because they get used for *commands* such as `/msg`. In those cases it is critical to complete from all users since limiting to just those in the current channel will be broken.

**Comment by jtdaugherty** [comment]
Another thing to note, since I forgot to clarify: tab-completion of `@` searches both the username and the full name, anywhere, case-insensitively. So `all` can be matched with any substring of `all`. We do this partly because that's what the web client does; you can then complete `@joe` from `@user<TAB>` for someone with the full name `Joe User`.

It looks like one way we do differ from the web client is that special things like `@all` are not matched quite so aggressively, so we could probably dial that back and only match those with prefix matches.

**Comment by setharnold** [comment]
On Thu, Jul 16, 2020 at 01:55:13PM -0700, Jonathan Daugherty wrote:
> Another thing to note, since I forgot to clarify: tab-completion of `@`
> searches both the username and the full name, anywhere,
> case-insensitively. So `all` can be matched with any substring of `all`.
> We do this partly because that's what the web client does; you can then
> complete `@joe` from `@user<TAB>` for someone with the full name `Joe
> User`.

I've found the various usernames vs names vs nicknames to be very
confusing. Having the nickname that I'm trying to tab-complete get
replaced by a username (or is it the other way around?) is probably part
of what adds to my feeling of unpredictable behaviour with tab-completion.

> It looks like one way we do differ from the web client is that special
> things like `@all` are not matched quite so aggressively, so we could
> probably dial that back and only match those with prefix matches.

What would you think about offering an alternative algorithm for folks
like me to rebind to our `<tab>` key, that does prefix-only and does the
lookup only on whatever name is shown in the chat window?

I think that kind of predictability would go a long way for me. :)

Thanks!

**Comment by jtdaugherty** [comment]
> I've found the various usernames vs names vs nicknames to be very confusing. Having the nickname that I'm trying to tab-complete get replaced by a username (or is it the other way around?) is probably part of what adds to my feeling of unpredictable behaviour with tab-completion.

Unfortunately we have the server application developers to thank for this design choice. Still, I see it as enormously helpful behavior, but it helps to *expect* it; and if it's surprising, it's definitely going to be confusing. One thing we can do is more clearly document the behavior, so at least it can be clarified.

> What would you think about offering an alternative algorithm for folks like me to rebind to our `<tab>` key, that does prefix-only and does the lookup only on whatever name is shown in the chat window?

 We could certainly look into that. The current behavior will need to stay the default, but we could add either an alternative key event or config file setting to govern the behavior.

**Comment by setharnold** [comment]
On Thu, Jul 16, 2020 at 04:22:25PM -0700, Jonathan Daugherty wrote:
> Unfortunately we have the server application developers to thank for
> this design choice. Still, I see it as enormously helpful behavior, but
> it helps to *expect* it; and if it's surprising, it's definitely going
> to be confusing. One thing we can do is more clearly document the
> behavior, so at least it can be clarified.

Indeed, it is very helpful to have a mapping of names to nicknames easily
available; in `irssi` I used a script `cgrep` to provide a similar
functionality when I was curious if a co-worker with a given name was
in the channel, and find what their nickname is, but those frustrations
are part of why we switched to mattermost.

>  We could certainly look into that. The current behavior will need to
>  stay the default, but we could add either an alternative key event or
>  config file setting to govern the behavior.

Excellent :D thank you!

**Comment by jtdaugherty** [comment]
@setharnold as of dc34ea3bad595ebfab60a9f94274ddc11d4d0bdc on the `develop` branch, now:
* `@all` and `@channel` are only matched if you type a prefix of either one (e.g. `al` or `ch`) rather than any substring.
* They are also listed *after* all other alternatives, so they are now the *least* likely completions.

Given that change, and our discussion above, I believe that addresses everything that came up here. Please close this if so, or let me know what else I forgot.

**Comment by setharnold** [comment]
Wow, I didn't expect that to be a two-line patch. That's really fantastic.

The other thing I would like is a binding for prefix-only tab-completion -- is that for a new issue, or this issue?

Thanks!

**Comment by jtdaugherty** [comment]
Unfortunately it is not quite as simple as prefix-only tab completion. The question is: prefix of *what*? Right now, tab completion for users, for example, matches substrings of both the username (or nickname) as well as the user's full name. That is how the web client behaves, and we develop Matterhorn by attempting to match the web client's behavior when we think it is sensible. That way, Matterhorn's behavior is hopefully not surprising to web client users.

I am glad the other changes we introduced on this ticket will be helpful to you. As far as alternative matching styles for tab completion are concerned, we will keep the current behavior as it is to maintain feature parity with the web client and avoid additional configuration that would be required to support it.

**Comment by setharnold** [comment]
On Mon, Jul 20, 2020 at 09:59:42PM -0700, Jonathan Daugherty wrote:
> That way, Matterhorn's behavior is hopefully not surprising to web
> client users.
> 
> I am glad the other changes we introduced on this ticket will be helpful
> to you. As far as alternative matching styles for tab completion are
> concerned, we will keep the current behavior as it is to maintain
> feature parity with the web client and avoid additional configuration
> that would be required to support it.

It's unfortunate, but I can see your point. Thanks so much for drastically
deprioritizing @all and @here, that alone will be a huge help. I'll just
have to learn to live with my confusions why `@thund<tab>` turns into
`@mike...` and double-checking that it expanded to the intended person.

Thanks
