### ISSUE TITLE
Enable help text to be searchable

### ISSUE THREAD

**Issue by benjaminselfridge** [matterhorn-chat/matterhorn#649]
It would be nice if you could search through the help screen to find topics rather than paging through and scanning with your eyes.

**Comment by jtdaugherty** [comment]
This has come up before, and we sorta kicked the can in that case by adding support to generate documents with keybindings and commands. But thinking on this now, I think that instead of adding search support to our help UI (which would be an enormous overhaul) it might be a smaller leap to instead display our help content in an external pager like `less`, which already has such support (and can also handle terminal escapes).

Doing this would require refactoring the help UI code to produce output suitable for `less`, rather than a `brick` `Widget` rendering, and then the help event handler would need to `suspendAndResume` the application while invoking an external pager.

**Comment by jtdaugherty** [comment]
Another idea, since we have a choice of a variety of formats, would be to generate `troff` and then use `man` as the pager; that could provide access to nicer presentation features rather than needing to do layout management ourselves.

**Comment by jtdaugherty** [comment]
(Generation would be key -- rather than just maintaining a static `troff` file -- because we want the help output to be dynamic in terms of the active configuration, so that it includes things like active keybindings and the current theme's attributes.)

**Comment by jtdaugherty** [comment]
To get a bit more specific on my proposal:
* Make `/help` and `/help <topic>` launch `man`
* Make the help UI rendering code emit `troff` instead of a `brick` UI; this mostly involves translating the markdown text to `RichText`, then converting that to `troff`
* Make the help event handler `suspendAndResume` to invoke `man`

**Comment by jtdaugherty** [comment]
Another benefit of this approach: it makes it possible to generate a static man page to be put into the releases and repo to be usable for the default Matterhorn configuration.

**Comment by jtdaugherty** [comment]
Since I was thinking of it:

https://cmd.inp.nsk.su/old/cmd2/manuals/unix/UNIX_Unleashed/ch08.htm

**Comment by jtdaugherty** [comment]
@benjaminselfridge and I talked and the first step on this is to start working on a `troff` Haskell package to represent and serialize Troff documents.

**Comment by benjaminselfridge** [comment]
Currently working on this here: https://github.com/matterhorn-chat/matterhorn/tree/feature/pandoc

The new plan is to write the help in Pandoc's AST so that we can convert it to any format supported by that library.

Current status:
* MH Help -> Pandoc -> HTML pipeline is functional, but I've only implemented 2/5 help topics in their entirety
* "Look" of HTML is drab/lame; can't figure out how to export a full HTML document (rather than just the bare minimum tags to render the help texts)
* Would like to include a markdown-style CSS
* Other backends would also be nice (troff, pdf, etc.)
* I had to move a bunch of code around to avoid import cycles; not all of this may have been necessary, and JTD and I will take a closer look at it soon

**Comment by jtdaugherty** [comment]
Thanks, @benjaminselfridge!

**Comment by jtdaugherty** [comment]
While merging `develop` into the branch mentioned above just now, I discovered that `pandoc` is licensed under the GPL. That's bad because it means that if we were to use `pandoc` and ship Matterhorn with that integrated, we'd be in violation of the GPL because Matterhorn is licensed under a BSD license. (This already happened once with `skylighting` and the "solution" was to split out the bits we needed into `skylighting-core` and license that as BSD.)

This discovery means that we cannot ultimately release this work until either 1) we license Matterhorn under the GPL, 2) `pandoc` changes its license (unlikely), or 3) we manage to find an alternative library or set of libraries that let us accomplish the same things without introducing a GPL dependency.

**Comment by benjaminselfridge** [comment]
Sounds good -- I think this was a nice proof-of-concept, but ultimately isn't super crucial and would be fun to pick up at a later date.

**Comment by jtdaugherty** [comment]
Thinking about this a bit more, I think just moving to [commonmark](https://hackage.haskell.org/package/commonmark) as the help text representation would probably be adequate. (I.e. extended Markdown.) From Commonmark we can produce HTML and could write translators to other formats as needed. The license on `commonmark` and `commonmark-extensions` is BSD-based so that is compatible with Matterhorn's license.

@benjaminselfridge - can you think of any reasons why this would be a problematic step down from Pandoc? I know Pandoc is super feature-rich, but if I recall, the main benefit we were wanting from Pandoc was the vast array of preexisting conversations that are already implemented.

**Comment by jtdaugherty** [comment]
As a follow-up note on `commonmark`, there's also [commonmark-pandoc](https://hackage.haskell.org/package/commonmark-pandoc) which allows Markdown to be parsed into the Pandoc types. That depends only on `pandoc-types`, which is BSD-licensed. If we're going to use `commonmark` then we will need something like this library anyway because the core commonmark library does not provide any concrete AST types -- it only provides type classes to parse into types of your own design. So this package could be useful in bridging to Pandoc types even if we're going to write our own converters. (`commonmark` provides an HTML converter already, so we wouldn't need to write that one.)

**Comment by jtdaugherty** [comment]
Looking into this more, I'm not sure how much benefit `commonmark` can provide. What it gives us is an HTML renderer, but *only* if the markdown input text is parsed directly into its HTML representation. If we're going to use Pandoc as our AST representation, we can't benefit from the HTML renderer in `commonmark` at all; we need to use some Pandoc-to-HTML converter instead. So I don't think `commonmark` buys us anything.

**Comment by jtdaugherty** [comment]
I'm going to close this as dormant and part of a large effort that would need to be undertaken. We don't get enough requests for this to make it a high priority. Let's re-open this later if work on this resumes.
