### ISSUE TITLE
Make channel selection mode display channels more consistently with the normal sidebar

### ISSUE THREAD

**Issue by benjaminselfridge** [matterhorn-chat/matterhorn#651]
Currently, when you type C-g, the channel highlighting goes away which normally indicates which channels contain unread messages. I think it would be nice if the search kept those highlightings.

**Comment by jtdaugherty** [comment]
To be consistent with the channel sidebar appearance outside of `C-g` mode, it would be good to apply the same logic that we use for the regular sidebar, including:
* Unread status attribute
* Mention count and attribute
* Previous channel sigil (`<`) and first-unread channel sigil (`~`)

Doing this will require a somewhat careful refactoring of `Draw.ChannelList` as well as potentially impacting the data types involved (`ChannelListEntryData` and `ChannelSelectMatch`). Right now there is some duplication as the different sidebar rendering modes share some but not all logic, out of necessity due to how the channel select results (`C-g`) are rendered.

**Comment by benjaminselfridge** [comment]
https://github.com/matterhorn-chat/matterhorn/tree/feature/channel-select-consistency

**Comment by jtdaugherty** [comment]
Thanks!

**Comment by jtdaugherty** [comment]
Looking at my comment above, it appears that:
* The unread status attribute is now applied as of Ben's branch
* The mention count is not preserved (but I don't think the attribute *should* be due to clashing with the selection mode attributes)
* The previous channel and first-unread channel sigils are already shown in `C-g` mode (so nothing to do here)
* The channel mute status is not preserved

@benjaminselfridge would you be willing to also add the mention count decoration as well as the mute status?

**Comment by benjaminselfridge** [comment]
Yep -- I wanted to first get your eyes on it to make sure it looked good to you before implementing the other features. I'll ping you when I'm done with the others.

**Comment by jtdaugherty** [comment]
Okay, thanks!

**Comment by benjaminselfridge** [comment]
This is now completed and merged into develop: 0f1dc386bd71cc6dfee07971285c389438d96df7

**Comment by jtdaugherty** [comment]
Thanks @benjaminselfridge!

**Comment by benjaminselfridge** [comment]
I'm reopening this because it it may be worth investigating whether we should also keep other coloring and sigils, particularly for the Direct Message listing at the bottom, when in channel selection mode.

**Comment by jtdaugherty** [comment]
I'm going to close this due to low urgency and being short on time to do it. We can re-open if it becomes an issue.
