### ISSUE TITLE
Investigate how/whether we can support Mattermost's Markdown table syntax

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#654]
Table rendering in Matterhorn is functional but it doesn't look as nice as the Web UI, e.g.:

![table-matterhorn](https://user-images.githubusercontent.com/22205322/90644016-2a0aa300-e22c-11ea-83d7-1c363302c0a9.png)

vs.

![table-webui](https://user-images.githubusercontent.com/22205322/90644033-3131b100-e22c-11ea-83bf-cb8a1e8b2408.png)

The problem doesn't appear to be Emoji, it's reproducible with the example below, adapted from [Mattermost's own documentation](https://docs.mattermost.com/help/messaging/formatting-text.html#tables):

```
| Left-Aligned  | Center Aligned  | Right Aligned |
| :------------ |:---------------:| -----:|
| Left column 1 | this text       |  $100 |
| Left column 2 | is              |   $10 |
| Left column 3456789 | centered        |    $1 |
```
which renders as:

![table-example](https://user-images.githubusercontent.com/22205322/90644894-35aa9980-e22d-11ea-9fb6-b8b2295fd230.png)

**Comment by jtdaugherty** [comment]
This is due to the fact that [the Markdown parser library that we use](http://hackage.haskell.org/package/cheapskate) does not support parsing tables in Markdown. We're likely to be migrating away from that library to [`cmark`](http://hackage.haskell.org/package/cmark) in the future, but I can't provide a timeline for that migration right now, and unfortunately `cmark` also doesn't support tables. (I don't find this too surprising, as Markdown's basic standard does not provide tables and all tables that got added are extensions.) Still, when we get to the point of moving to `cmark`, I'd be happy to ask the maintainer if table parsing support could be added.

I do need to point out that the emoji you used will still cause rendering problems even once we support tables, but that's [a different issue](https://github.com/matterhorn-chat/matterhorn/issues/569) that we'd ultimately also like to resolve.

**Comment by jtdaugherty** [comment]
After doing some more research, it's clear that `cmark` will not be able to support tables unless tables get added to the [CommonMark specification](https://commonmark.org/).

**Comment by jared-w** [comment]
Is commonmark-hs performant enough to be considered? It's pure haskell, used by pandoc, and offers a full range of markdown extensions as well as an easy way to traverse the AST and add your own logic should Mattermost extend markdown later.

**Comment by jtdaugherty** [comment]
@jared-w do you mean this? http://hackage.haskell.org/package/commonmark

**Comment by jtdaugherty** [comment]
To follow up, I just asked because there isn't any package called `commonmark-hs` so I was initially confused. I hadn't heard of this package. It's intriguing that it aims to be extensible and the set of existing extensions looks great. That seems like a good candidate for us to try. If anyone wants to give it a spin, the work to be done is to update the `cheapskate` AST translation in `Matterhorn.Types.RichText` first. If that goes well, then we can try out integrating the table extension and extending `RichText` to represent tables.

**Comment by jtdaugherty** [comment]
Thanks for finding that, @jared-w!

**Comment by jtdaugherty** [comment]
Since we already have an older ticket open about a more general statement of this problem, I'm going to close this and update #556 to mention table support. Thanks, everyone!

**Comment by jtdaugherty** [comment]
Now that `commonmark` support has been merged to `develop`, we are in a position to explore supporting the pipe table extension provided by `commonmark-extensions`.

**Comment by jtdaugherty** [comment]
Support for pipe tables has been merged to `develop` (a while back, actually). It will be included in the next release!
