### ISSUE TITLE
Matterbridge text invisible

### ISSUE THREAD

**Issue by Amolith** [matterhorn-chat/matterhorn#675]
I'm not entirely sure whether this is a bug with [Matterbridge](https://github.com/42wim/matterbridge/) or Matterhorn but I'm inclined to think it's the latter because text is rendered fine in the web UI.

My organisation has a bot that bridges a few of our channels with another group's on Slack. In the web UI, the messages look like this:
![Screenshot of a conversation between me and a friend. My messages render as normal but his are sent by the user "slack-bridge" with his name to the left of the message he sent, somewhat similar to IRC](https://user-images.githubusercontent.com/29460675/95799090-97353480-0cc1-11eb-9e92-cdc6b54a00c4.png)

While text from the bot is invisible within Matterhorn:
![image](https://user-images.githubusercontent.com/29460675/95799209-f5faae00-0cc1-11eb-970c-8f2a2d090e59.png)

I thought it might be my theme (recently switched to light and broke some other TUI apps) so I tried highlighting text as it usually changes colour and is revealed. However, it looks exactly the same and that makes me think Matterhorn just isn't rendering it at all.
![image](https://user-images.githubusercontent.com/29460675/95799291-3528ff00-0cc2-11eb-9117-9563a7f367c8.png)

We're currently using Mattermost v5.26.1 and I have Matterhorn v50200.10.1 installed. I'm happy to provide more info if necessary!

**Comment by jtdaugherty** [comment]
It depends on how the bot is packaging the message text. Matterhorn doesn't render text unless it appears in the post body, and some plugins put the text elsewhere in the post data structure. If you could use a Javascript debugger to get the contents of one of these posts from your browser as it comes over the HTTPS connection, that would be helpful for us to track this down.

**Comment by Amolith** [comment]
> If you could use a Javascript debugger to get the contents of one of these posts from your browser as it comes over the HTTPS connection, that would be helpful for us to track this down.

Would you mind providing brief guidance for that? I'm familiar with the network, inspector, and console tools but I've never worked with the JS debugger before.

**Comment by Amolith** [comment]
Unless this is what you're referring to:
![image](https://user-images.githubusercontent.com/29460675/95802958-d87f1180-0ccc-11eb-9e5e-c25ed0743543.png)

**Comment by jtdaugherty** [comment]
@Amolith I'm looking for the JSON content of the post that comes back from the server. To get that you'll have to look in the Inspector's network traffic tab in your browser, and click through the various requests. If these messages are coming in as you are watching, the easiest place to see them would be to look at the Websocket event stream (which shows up under the "WS" tab of the Chrome network inspector).

**Comment by Amolith** [comment]
@jtdaugherty I replaced the user's name with `USERNAME`. Everything else is pasted directly. Is this the content you meant?

```json
"9ph4u65e87dsxm5r3w3psgnrqo": {
	"id": "9ph4u65e87dsxm5r3w3psgnrqo",
	"create_at": 1602555014924,
	"update_at": 1602555014924,
	"edit_at": 0,
	"delete_at": 0,
	"is_pinned": false,
	"user_id": "iqx1ouqdmigbi8w397zoxf3emw",
	"channel_id": "q7k7zgjqd3f57qx9r9konzaqrh",
	"root_id": "",
	"parent_id": "",
	"original_id": "",
	"message": "[**USERNAME**]: Sounds good. I'll let you know the results on Wednesday. That will give everyone time to vote.",
	"type": "",
	"props": {},
	"hashtags": "",
	"pending_post_id": "",
	"reply_count": 0,
	"metadata": {}
},
"a8n7i6hhpbndtmjuemkxaizaqy": {
	"id": "a8n7i6hhpbndtmjuemkxaizaqy",
	"create_at": 1602554786287,
	"update_at": 1602554786287,
	"edit_at": 0,
	"delete_at": 0,
	"is_pinned": false,
	"user_id": "iqx1ouqdmigbi8w397zoxf3emw",
	"channel_id": "q7k7zgjqd3f57qx9r9konzaqrh",
	"root_id": "",
	"parent_id": "",
	"original_id": "",
	"message": "[**USERNAME**]: I'll make a poll about merging more channels. I just thought the single channel bridge was good enough. It might increase conversation for both clubs though.",
	"type": "",
	"props": {},
	"hashtags": "",
	"pending_post_id": "",
	"reply_count": 0,
	"metadata": {}
},

```

**Comment by jtdaugherty** [comment]
Yes, that's what I was looking for. It turns out that the syntax used by `matterbridge` is valid Markdown and is treated as a *reference-style link* as described here:

https://www.markdownguide.org/basic-syntax/#formatting-the-second-part-of-the-link

Reference-style links are not supported by our Markdown parser, so when our Markdown parser sees this message, it fails to parse (and does not yield an error). The particular bit that is confusing the parser is square brackets followed by a colon; if the colon or brackets are removed, the issue goes away and the message appears as expected.

This is arguably a bug in *both* our parser (the `cheapskate` Haskell library, which we do not maintain) as well as Matterbridge. I think the library should be more graceful even if it fails to parse this, but I also think Matterbridge should pick a syntax that does not have an unintended meaning. Unfortunately Markdown is a disaster from a standardization standpoint because it's hard to decide on what constitutes valid Markdown, but there we are.

I will follow up with the Cheapskate maintainer for that half of this.

**Comment by jtdaugherty** [comment]
Correction: `cheapskate` *does* support reference links and those references are indeed parsed but have no visual representation in the rendered documents. Our message-rendering doesn't support them (because why on earth would someone put that in a Mattermost message?) so that results in what is effectively an empty message.

**Comment by Amolith** [comment]
> if the colon or brackets are removed, the issue goes away and the message appears as expected

We can fix that on our end then; Matterbridge allows you to define how messages from remote platforms are displayed in the config file.

> I also think Matterbridge should pick a syntax that does not have an unintended meaning

I think that was an unintentional mistake on our part haha. The [default format](https://github.com/42wim/matterbridge/blob/master/matterbridge.toml.sample#L157) is `[protocol] <nick> message` but we're not bridging any platforms other than Mattermost and Slack so we shortened it and added a colon for clarity.

I appreciate the help!

**Comment by jtdaugherty** [comment]
I'm glad you have a way to fix this now, and you're welcome!
