### ISSUE TITLE
Using Paths_matterhorn for data files

### ISSUE THREAD

**Issue by VannTen** [matterhorn-chat/matterhorn#683]
Would you consider using Paths_matterhorn (the module generated by Cabal) for
`data-files` ? (and adding emoji.json to those)

Currently the data-files are located at the same place than the executable.

# Benefits

That would allow the install / packager to specify where to place these files ;
that would be make it easier to have native packages for various distributions.

# Problems
However, it might cause some problems with the development build and the current
way of doing releases.

I've started to modify the code to see how it would work and it does break at
least ./run.sh, but it works when I use `cabal run`. I understand that cabal
does not set the correct path in the auto generated module, but use env variables
in `run` to resolve to the correct path (`matterhorn_datadir` etc).

For binary releases, I assume it would also break, since during the build there
is now way to know where the tarbal will be extracted.

---------------------------------

An option would be to support both the current mechanism and the
Paths_matterhorn and the current mechanism but that adds some cognitive
overhead.

# Conclusion

Giving the disruption it would cause, I will understand if you do not wish to
merge such a change, and I'll maintain a patch on my own.

P.S. : By the way, Matterhorn works greats :).

**Comment by karljs** [comment]
I've investigated the implications of this suggestion.  It seems to be there are 4 different workflows we would ideally support: 
1. Users downloading the existing binary releases
2. Package maintainers trying to package for specific distros and repositories
3. Folks running development builds, such as via `run.sh`
4. Developers loading code in a `cabal repl`

Using a `Paths_matterhorn` module, in principle, appears to support these as follows:
1. Not at all
2. Fine, evidently.  I don't have personal experience with this.
3. Not well, because if we run the executable without cabal then the paths don't seem to be set correctly. 
4. Fine

Our current approach (look at the path of the executable and determine where to look for data files ourselves) seems to support the following:
1. Fine
2. Not well because it assumes data files will be in a sibling directory to the executable
3. Fine
4. Fine

@jtdaugherty Assuming you agree that we want to support those workflows, I think the thing to do might be to keep the current implementation as a default, but add a configuration flag to the cabal file that enables the use of a `Paths_matterhorn` module as a separate code path.  That way, package maintainers have a way of achieving what they need but we don't disrupt any of the current workflows that folks depend on.

**Comment by jtdaugherty** [comment]
Thank you for your investigation, @karljs. I could imagine adding a build flag to use the build paths. While I'm concerned that baking paths into the binary makes for a brittle approach, it would be okay if it composed well with the current method of finding data files.

I believe the only data files or directories that would be impacted by this change are:
* `emoji.json` (`Matterhorn.FilePaths.bundledEmojiJsonPath`)
* `syntax/`, i.e. the path to the XML specs directory (`Matterhorn.Config.getBundledSyntaxPath`)

I can't think of a reason why we couldn't just support *both* the build path as well as the default path(s), starting with custom paths in the config, then falling back to the build path, then finally falling back to the path relative to the executable. That would work for people running binary releases and it would also work for developer builds and distribution-based packaging, right?

**Comment by karljs** [comment]
You're definitely right that we could have a kind of cascading sequence of locations to check, and if we do that, I agree with your ordering.  My only gripe with this is that I prefer a single, canonical, sort of statically-known way of doing things.  While admittedly minor, I have a kind of irrational dislike for situations like:
- User installs from their distro package manager
- User decides they want a newer version, so uninstalls and grabs a binary release
- Package manager doesn't clean up fully and now the binary release is finding a mismatched set of syntax files installed elsewhere

All that said, we can probably avoid this kind of issue with care.

Just for the sake of exhaustive options, we could also use something like `file-embed`, although I suppose that would complicate user customization unnecessarily.

**Comment by jtdaugherty** [comment]
> Package manager doesn't clean up fully and now the binary release is finding a mismatched set of syntax files installed elsewhere

I also share a desire to avoid this; to me, the only way this would be a good thing is if the package manager really did remove what was in the package, but the user had installed newer data file(s) in, say, `~/.config/matterhorn/` or something like that, which would override the ones in the package anyway. To confirm, it sounds like you're talking about just making sure the package cleans up after itself, *not* something about user-overridable data files?

As for `file-embed`, that could be nice for small things, but it would not be a good idea (to me) for the XML files because that would greatly increase the binary size (which, even stripped, is already huge). And that doesn't get us off the hook for needing to find out where alternative data files could live on disk, I think.

**Comment by jtdaugherty** [comment]
I believe this is essentially complete with the merging of https://github.com/matterhorn-chat/matterhorn/pull/724.
