### ISSUE TITLE
Add "raw mode" to be able to copy current view text natively

### ISSUE THREAD

**Issue by 3v1n0** [matterhorn-chat/matterhorn#686]
While Using `yank` feature is ok if you need to copy one message at time, it's not enough if you want to copy many messages in your history.

It's possible to make it better by using `/toggle-channel-list`, but it doesn't work if you have to copy multi-pages.
Terminal clients such as Weechat have a "[bare display mode](https://blog.weechat.org/post/2014/02/16/Bare-display)" that allows to enter in a non-visual mode that allows to do such operations as acting to a native terminal content.

Also for some reason, when using native terminal copy & paste, messages are not separated by a new line.

**Comment by jtdaugherty** [comment]
> While Using yank feature is ok if you need to copy one message at time, it's not enough if you want to copy many messages in your history.

Is this ticket then a request to support some mechanism for copying multiple messages at a time?

**Comment by 3v1n0** [comment]
Eventually yes, but a "bare" mode would also allow to easier use URLs without having to use `C-o`

**Comment by jtdaugherty** [comment]
Okay, now I'm really confused. So is this ticket about making it easier to click on URLs?

**Comment by 3v1n0** [comment]
Both :)

The issue is about having a bare view as weechat does that would allow both, between the others.

**Comment by jtdaugherty** [comment]
Okay. I ask because it is helpful to understand the underlying concern that you want to address; just because weechat does something doesn't mean we can, or want to. In this case I am not yet willing to consider a "bare mode" as you mention.

If your main concern is opening URLs more easily, have you tried terminal-supported hyperlinks? To try that, you can set `hyperlinkURLs = True` in your configuration and use a terminal emulator that supports them.

**Comment by 3v1n0** [comment]
Sure, and hyperlinks work fine.

In general though, URLs are the minor issue here (a part that if you're reading the backlog and , as I stated in the first comment, the primary problem is being able to copy & paste big chunk of history.

Maybe an easier option would be something like `/log-snapshot` but for the chat log instead?

**Comment by jtdaugherty** [comment]
I'm glad hyperlinks are working for you.

As far as message logging, there is an open ticket for that, so we can consider that already filed: https://github.com/matterhorn-chat/matterhorn/issues/583

On a more general note, it would be really helpful when filing tickets if you could focus more on the problem you would like us to help you solve rather than proposing specific solutions. Starting with solutions means we have to infer what the problem is (as we had to do here) and that can lead to confusion (as it did here for me). In addition, it can be unhelpful to debate solutions when we just don't like the solution you proposed *even if we actually care about helping you with the problem*.

If the problem is being able to copy and paste history of incoming messages, then the question becomes whether logging messages takes adequately good care of that concern. I believe it does. If you disagree, then let's dig into more about why that doesn't address your concern, and file a new ticket for that.
