### ISSUE TITLE
nickname colouring in messages breaks on '-'

### ISSUE THREAD

**Issue by jtroup** [matterhorn-chat/matterhorn#687]
I've noticed colleagues who have '-' in their nickname, don't have their nickname coloured when other user reference them in messages.  Messages from them will correctly colour their own name, so e.g.:

```
@alice-user: a question
@bobtaf: @alice-user an answer
@alice-user: @bobtaf a followup
```

```@alice-user``` will be in colour for the first and third line but not the second.
```@bobtaf``` is always in colour.

**Comment by jtdaugherty** [comment]
Thanks for the report!

**Comment by jtdaugherty** [comment]
@jtroup I looked into this, and it is happening because 1) nicknames are not valid in `@` references (even the web client does not do this) and 2) in your case if you are seeing a partial highlight, it's because there is a user whose username corresponds to the highlighted text. Any time a `@`-prefixed token appears in a message, matterhorn will only highlight it (and the web client will only link it) if it corresponds to an account username.
