### ISSUE TITLE
The release file aren't buildable

### ISSUE THREAD

**Issue by jvoisin** [matterhorn-chat/matterhorn#700]
```
wget https://github.com/matterhorn-chat/matterhorn/archive/50200.12.0.tar.gz
tar xzf 50200.12.0.tar.gz
cd matterhorn-50200.12.0 ./build.sh                                                                                                      
Config file path source is default config file.
Config file /home/user/.cabal/config not found.
Writing default configuration to /home/user/.cabal/config
When using configuration(s) from tmp/matterhorn-50200.12.0/cabal.project, the following errors occurred:
The package directory 'submodules/mattermost-api' does not contain any .cabal file.
The package directory 'submodules/mattermost-api-qc' does not contain any .cabal file.
```

This is problematic, since it prevents matterhorn from being built hermetically.

**Comment by jtdaugherty** [comment]
Hi @jvoisin, thanks for the report! It's interesting that you point this out, because it's accidental that `build.sh` is included in releases. The releases are binary-only and are not intended to be built from source. If you want to build from source, you'll need to build from a clone of the repository; for details on how to do that, see `docs/BUILDING.md`. I'm going to update our releases so that they do not include `build.sh`.

**Comment by jtdaugherty** [comment]
I deleted my previous comment where I misunderstood what was happening here. If you want to build from source, please see `docs/BUILDING.md`. Building from the source distribution that you mentioned above is possible but will require some additional steps; for best results, please follow our build instructions. Let me know if you run into any other issues!

**Comment by jtdaugherty** [comment]
Another way to build from source that is already supported is to just use `cabal`, since `matterhorn` and its dependencies are published to `hackage.haskell.org`. For that, you should be able to just `cabal install matterhorn`.

**Comment by jvoisin** [comment]
Unfortunately, this won't work for packaging matterhorn: most of linux distribution package build system are expecting an archive with the source, and build a package from it.

Also, as for `cabal install`: the builder doesn't have access to internet, so it won't work.

**Comment by jtdaugherty** [comment]
Can you provide some details about what you are trying to accomplish?

**Comment by thestr4ng3r** [comment]
This problem is quite common with the tarballs that GitHub automatically generates on tags, since it ignores submodules. One common solution is to have a CI job generate a tarball with everything included, see for example https://github.com/thestr4ng3r/chiaki/issues/3 https://github.com/thestr4ng3r/chiaki/commit/08f5a3d4bf537b25dc385a35b6351c80afef86de
It depends on what kind of packages you want to provide for every release I guess.

**Comment by jtdaugherty** [comment]
Yes, I think that's essentially the issue here; we don't have control over how those tarballs get built. We already provide other avenues for building Matterhorn, and in any case, if someone wants to package Matterhorn for a particular distribution, it won't matter much what our release process is anyway because the maintainer for that distro package will have to do some work to create an archive that meets the requirements of the distribution in question.

In summary, we do not support the source archives that github produces, so please do not expect them to work. Instead, please clone the repository and follow the instructions in `docs/BUILDING.md`. We regularly test and maintain those instructions. I'd also be happy to extend them a bit if distribution-specific build instructions would be more appropriate. We support building Matterhorn on a variety of platforms (for our binary releases), and some of the necessary steps for building Matterhorn on those platforms can be found in `setup/setup_linux.sh`.

**Comment by XVilka** [comment]
@jtdaugherty we could send a pull request for your CI to generate source tarballs for every release with GitHub Actions, then upload formed tarballs as we do for Rizin, for example, https://github.com/rizinorg/rizin/blob/dev/.github/workflows/ci.yml#L398

**Comment by jtdaugherty** [comment]
@XVilka I still do not yet understand from what concern(s) need to be addressed. Until I am clear on that, I cannot evaluate solutions. It would help me to know two things:
* Are @XVilka and @thestr4ng3r and @jvoisin all jointly involved in the same effort?
* What are you trying to accomplish?

**Comment by XVilka** [comment]
@jtdaugherty @jvoisin packaging Matterhorn for Alpine Linux, me and @thestr4ng3r are daily Matterhorn users.

**Comment by jtdaugherty** [comment]
Okay, thanks @XVilka!

**Comment by jtdaugherty** [comment]
With the clarification from @XVilka, the only thing that remains is some clarification from @jvoisin on what else is in the way. I did want to follow up on one comment:

> Also, as for cabal install: the builder doesn't have access to internet, so it won't work.

This is going to be a problem for building any Haskell-based software, since doing such builds requires fetching potentially hundreds of dependencies from `hackage.haskell.org`. The only way to avoid that is to use a GHC installation with a package database that includes those dependencies already, which means all of Matterhorn's dependencies (transitively) will need to be present. That likely means they'd need to be available in Alpine packaging format. Do you have experience packaging other Haskell software on Alpine?

**Comment by kquick** [comment]
In particular, the initial report describe missing the _dependencies_ of matterhorn (which are customarily found in the directories populated by a `git submodule` checkout. 

An OS packaging process should normally package all the dependencies of an application and make those available to the package when building, or else fetch the source of all dependencies so that they are available to the build process.  While it's true that a hermetic build should not have internet access during the _build_, there should be a fetching stage where the package to be built and all dependencies are retrieved prior to the build.

**Comment by jvoisin** [comment]
[This]( https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/testing/matterhorn/APKBUILD ) is how the Alpine package is built, and it's gross.

I would like to be able to build a matterhorn package in isolation, but it's not possible at the moment, due to the sheer amount of dependencies, and the fact that they're not (yet?) packaged in Alpine yet.

As for using git, this is frowned upon, and we would *strongly* prefer a tarball.

So, pulling dependencies at build time is ok-ish, for the moment. What is the right™ way to build a matterhorn binary, from the available tarball?

**Comment by kquick** [comment]
I'm not sure what your aesthetics are, so I don't know how to interpret "it's gross", but looking at it I would say that it has only collected the dependencies available from Hackage, not the non-Hackage dependencies that are represented by the submodules.

You can fetch tarballs for those dependencies in the same manner that you fetched the matterhorn tarball, unpack them in the location that the `cabal.project` expects to find them, and then run your build.

**Comment by kquick** [comment]
On further reflection, the dependencies referenced by the cabal.project file are also available on Hackage, so it may also be possible to remove the cabal.project file before running your build process and satisfy the dependencies that way as well.

**Comment by thestr4ng3r** [comment]
@jvoisin Also be aware that hackage also supplies tarballs for every package directly without having to use cabal to fetch them, e.g. https://hackage.haskell.org/package/matterhorn-50200.12.0/matterhorn-50200.12.0.tar.gz
These are the source packages produced by `cabal sdist` which are pretty much standardized tarballs for haskell packages.

**Comment by jvoisin** [comment]
I managed to use the 3 archives to get the package to build with the modern cabal: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/19554

Thanks everyone!

**Comment by jvoisin** [comment]
Unfortunately, it takes more than one hour (!!!) to build matterhorn, reaching Alpine's builder limit.
Is there a way to speed up the compilation process?

**Comment by kquick** [comment]
You might build dependencies as separate packages.

**Comment by jtdaugherty** [comment]
> Unfortunately, it takes more than one hour (!!!) to build matterhorn, reaching Alpine's builder limit.

@jvoisin If you're building all of the dependencies each time, then yes, that would be akin to building Glibc whenever you want to build any C program. Is there any way to cache the results of building the dependencies, without caching the build of Matterhorn itself?

(The short answer to your question is no, in general we are not going to be able to do much about the build times aside from getting rid of heavyweight transitive dependencies. If anything the dependency set will only get larger over time; there is a branch of Matterhorn right now that adds an additional 15 minutes of build time.)
