### ISSUE TITLE
/focus ~ doesn't show up available private channels

### ISSUE THREAD

**Issue by ajayeeralla** [matterhorn-chat/matterhorn#703]
I've realized lately that `/focus ~` only shows available public channels, but not the private channels.

**Comment by jtdaugherty** [comment]
Thanks for the ticket! I just want to clarify one thing: when you say "available", do you mean "private channels that the user is a member of already?" (I read "available" to mean "all private channels on the server that the user *could* join, but are not yet a member of".)

**Comment by ajayeeralla** [comment]
@jtdaugherty Yes you're right, the user's private channels I meant.

**Comment by jtdaugherty** [comment]
Okay, thanks for the clarification.

**Comment by jtdaugherty** [comment]
The code at issue is the channel autocompletion code. That code uses the server's "autocomplete" API endpoint for channels. The documentation says that that will only return public channels. So we need to either find an alternative API endpoint that does what we want, or cobble something together from other API responses or just by looking at the collection of channels in the application state.

Another thing I need to mention is that changing how autocompletion works for channels will change it for *every* use of `~` in the editor, because our completion is not context-sensitive. So we'll also need to think about whether any proposed changes result in nonsensical/undesirable completion behavior in other contexts.

**Comment by ajayeeralla** [comment]
> The code at issue is the channel autocompletion code. That code uses the server's "autocomplete" API endpoint for channels. The documentation says that that will only return public channels. So we need to either find an alternative API endpoint that does what we want, or cobble something together from other API responses or just by looking at the collection of channels in the application state.
> sure.
> Another thing I need to mention is that changing how autocompletion works for channels will change it for _every_ use of `~` in the editor, because our completion is not context-sensitive. So we'll also need to think about whether any proposed changes result in nonsensical/undesirable completion behavior in other contexts.
I'm wondering what are the other uses of `~` apart from being present in channel URL names.

**Comment by jtdaugherty** [comment]
Any command that takes a channel name would be an example. Right now `/join` is another example, but more could be added in the future. (And even in the `/join` case, the context-sensitive completion would be channels we *aren't* a member of, so that would have to be changed anyway.)

**Comment by jtdaugherty** [comment]
I'm going to close this due to low urgency. If someone wants to work on it, let's re-open it.
