### ISSUE TITLE
matterhorn for matrix?

### ISSUE THREAD

**Issue by evils** [matterhorn-chat/matterhorn#713]
hi

with the recent upheaval in IRC, i've been quasi forced to start using matrix chat

unfortunately i've not found a matrix client that i like

i do however use matterhorn and think it's the best chat client i've ever used

hence my question:
has adapting the matterhorn to work with matrix been suggested/considered?

**Comment by jtdaugherty** [comment]
Hi @evils, we're glad to hear that you're enjoying Matterhorn, thank you! As far as Matrix is concerned, we have talked about it off and on. So far our conclusion has been that supporting Matrix would involve a more or less complete overhaul of Matterhorn since so much of it is built specifically to work with the Mattermost server API and client design. We've invested pretty heavily in a design that we hope works well for Mattermost (emulating the web client when possible) so I don't think Matrix support is likely to end up on our roadmap. To add to that, our employer, Galois, Inc., currently supports all of our maintenance that isn't done in our spare time or with the help of the community. We use Mattermost at work, so naturally we have a vested interest in a good client there.

With that said, the usual open-source project caveat applies: although the core development team is unlikely to have the resources or motivation to support Matrix, we would be willing to work with any community member(s) who wanted to investigate what it would take and we would be happy to work with them on an assessment about whether it would be possible to generalize the client in a way that would be compatible with our core mission, which is to provide a Mattermost client that matches the official web client's features reasonably well.

**Comment by VannTen** [comment]
> With that said, the usual open-source project caveat applies: although the core development team is unlikely to have the resources or motivation to support Matrix, we would be willing to work with any community member(s) who wanted to investigate what it would take and we would be happy to work with them on an assessment about whether it would be possible to generalize the client in a way that would be compatible with our core mission, which is to provide a Mattermost client that matches the official web client's features reasonably well.

Hi.

I also was once a user of matterhorn, but now using matrix at work instead of mattermost. As @evils, I can't find a matrix client filling my needs, and I was quite fond of matterhorn. So, I'd like to work on this.

I've started to take a look at the matterhorn code to see where to start.

From my (for now, quite shallow) understanding, `ChatResources` seems like a good place to start as it holds "configuration and connection-related information". 

I presume I should also take a look a `Connection.hs` ?

If you have any pointers on where the most of the interaction with `mattermost-api` is, I'll appreciate it. (I presume this where the most of the work should be to adapt it to the Matrix API). (Or on anything else, by the way).

-------
On a higher level, do you have opinions on what the best path would be ?
- forking to a new project and replacing the mattermost specific parts with matrix ones.
- work on generalizing matterhorn directly => I guess this might be more work and might not be valuable to you as you explained in your previous comment.

Thanks for reading me
And for matterhorn :+1:

**Comment by jtdaugherty** [comment]
Hi @VannTen. Before looking too closely at the code, I think it would be important to start with a comparison of the abstractions that the different services use and the different ways that they organize information. That will be important to help me provide some information on how much of an overhaul Matrix support would entail, and therefore how feasible it is.

I also want to mention that supporting a completely different server backend would ultimately require us to generalize the application frontend and factor it out of the current package. This would be no small feat, but it would be necessary because we'd need to have split maintenance for different services (i.e. I am not in a position to support a client that uses Matrix since I don't use Matrix, and presumably anyone with lots of time to maintain Matrix support is not interested in maintaining Mattermost support).

Right now I am the maintainer for `matterhorn` and its only developer. In the past we had a team of three to four people (where I work) working on the client, but over the years those folks have moved on to other work and I'm the only person who works on Matterhorn. I am also very limited on time, which is the main reason why Matterhorn has not seen much activity over the last several months. That is not likely to change soon, although I hope at least to put in some of my spare time fixing bugs as I'm able.

I share that context because it's important background for my deeply-held belief that supporting a totally different service in this client codebase is either going to be a *lot* of work or not possible without basically going back to square one. As the only person with a deep knowledge of all of the code, I feel compelled to share this assessment as the only person who knows enough to have an opinion about what might be possible. I wanted to make this very clear now because as much as I think it's great that people like Matterhorn enough to want to use it for other services (yay!), I want to set realistic expectations about the possibility of actually doing so, and I want to set expectations about my own (lack of) availability to help out.

In my opinion, Mattermost has a number of design aspects that would, in all likelihood, have turned out differently had the program been designed from the protocol up (as I understand Matrix was). In my experience, this means it's likely that supporting a system like Matrix might make for a relatively clean application design while supporting Mattermost would require some compromises, and supporting both in the same codebase would lead to some abstraction mismatches that would be difficult to resolve. I could be wrong, but given what I know about how Matterhorn was developed and what I know about its design, I'd just be very surprised if it could be cleanly mapped onto Matrix.

As to the specific question you asked about API usage, the answer is, in some sense, "all over the place." Modules in the `State` hierarchy of the module list are the ones where most of the API calls are being made, although they're mostly made in the context of our asynchronous worker machinery. You can see them by their (usually) qualified imports from `mattermost-api`.

Anyway, as I said at the start, it would be good to first study the Mattermost server API and design and see how that does or doesn't map onto how Matrix models things. That would be an easy way to raise any obvious concerns about show-stopping abstraction mismatches.

**Comment by jtdaugherty** [comment]
I wanted to follow up and say that I realize my comment might be discouraging, and I suppose in a way that's my intention; I don't have the time and resources to turn `matterhorn` into `libpurple`, as much as that might be cool, and since nobody else is involved in the project deeply enough to take on the work that would be required, that means it would fall to me.

The best path really might be to build a Matrix client using some of the same technologies we used, but doing it "right" from the ground up in a way that really works well for Matrix's design. You could borrow whatever design ideas from Matterhorn that you wanted. If someone wanted to do that, I'd be happy to help with the UI since I am the maintainer/developer of the UI libraries that we use in Matterhorn.

**Comment by jtdaugherty** [comment]
(I should also mention that `libpurple` already has both a text-based client -- `finch` -- and a plugin for Matrix.)

**Comment by VannTen** [comment]
> Hi @VannTen. Before looking too closely at the code, I think it would be important to start with a comparison of the abstractions that the different
> services use and the different ways that they organize information.

Agreed. I'll need to thoroughly look at the Matrix API anyway ; I'll try to report what differences I can discern. Although, I might not complete that
if I rather start from scratch (which looks like the best path forward from your postings).

> I wanted to follow up and say that I realize my comment might be discouraging, and I suppose in a way that's my intention; I don't have the time and
> resources to turn `matterhorn` into `libpurple`, as much as that might be cool, and since nobody else is involved in the project deeply enough to
> take on the work that would be required, that means it would fall to me.
 
Hi, and thanks for the assessment. It's not discouraging, in fact, I kinda expected that matterhorn would be too deeply entrenched with the Mattermost API.
Thanks for taking the time to write this up, that was precisely what I was searching by posting here, before investing a lot of time into this. 

> The best path really might be to build a Matrix client using some of the same technologies we used, but doing it "right" from the ground up in a way
> that really works well for Matrix's design. You could borrow whatever design ideas from Matterhorn that you wanted. If someone wanted to do that,
> I'd be happy to help with the UI since I am the maintainer/developer of the UI libraries that we use in Matterhorn.

I'm gonna try that path. That will gave me the opportunity to work on the design of a big Haskell project on my own (that's new). I'll let you know
how that ends up !

I presume the UI libraries you mention are Vty and Brick ?

**Comment by jtdaugherty** [comment]
> I kinda expected that matterhorn would be too deeply entrenched with the Mattermost API.

In my view it's not just the API; more importantly in my view, it's about the way the server arranges information (e.g. into teams, channels of different types, etc.) that leads to a particular client application design.

> Thanks for taking the time to write this up, that was precisely what I was searching by posting here, before investing a lot of time into this.

I'm glad it was helpful!

> I presume the UI libraries you mention are Vty and Brick ?

Yes, that's right. `vty` takes are of relatively low-level things (providing access to user input events and drawing to the screen) while `brick` provides higher-level abstractions and UI layout.
