### ISSUE TITLE
Unexpected error, no route to host

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#714]
Hello, matterhorn gave me an error message:

```
An unexpected error has occurred! The exception encountered was:
  HostCannotConnect "chat.canonical.com" [Network.Socket.connect: <socket: 15>: does not exist (No route to host),Network.Socket.connect: <socket: 15>: does not exist (No route to host)]
Please report this error at https://github.com/matterhorn-chat/matterhorn/issues
```

It seems that matterhorn had reconnected without my intervention.

I have Popey's snap installed, version `50200.12.0-42-gb87270a8`.

Thanks

**Comment by jtdaugherty** [comment]
Thank you for the report! This is now fixed in `develop` and will go out in the next release. ("Fixed" here just means that Matterhorn will not report this as an unexpected error; otherwise, the behavior is unchanged inasmuch as `matterhorn` will attempt to reconnect to the server once the connection is working again.)

**Comment by setharnold** [comment]
Cool, thanks :)
