### ISSUE TITLE
differences in rendering codeblocks vs web interface

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#756]
Hello, code blocks may be rendered differently in matterhorn than in the mattermost webclient.

Note the `addressing` lines up with `debian` and `CVE` on the mattermost screenshot but not in the matterhorn screenshot.

Thanks

![matterhorn](https://user-images.githubusercontent.com/5447148/151035291-77e43681-ca16-4074-b462-fdc37e68e8bf.png)
![mattermost](https://user-images.githubusercontent.com/5447148/151035312-042321be-99f6-458f-81d2-3ad21033f8fd.png)

**Comment by jtdaugherty** [comment]
Can you provide the full text of the code block?

**Comment by setharnold** [comment]
Since it's mixed markdown it might render very oddly here:

```
Review request, is this ok for a changelog message:
```
  * SECURITY UPDATE: Information leak leading to session hijack vulnerability
    in Rack
    - debian/patches/CVE-2019-16782.patch: Squashed commit of multiple fixes
   addressing the information leak
    - CVE-2019-16782
```
The relevant patch is https://www.openwall.com/lists/oss-security/2019/12/18/2/2
```

**Comment by setharnold** [comment]
Okay that went poorly. Let's try an attachment instead.

[codeblock.md](https://github.com/matterhorn-chat/matterhorn/files/7938607/codeblock.md)

**Comment by jtdaugherty** [comment]
Thank you! I entered that into my Mattermost instance and compared the results. I don't see a difference.

Here's my web client's version:
<img width="621" alt="Screen Shot 2022-01-25 at 9 19 09 PM" src="https://user-images.githubusercontent.com/427221/151108112-82834edc-c861-42eb-9669-dce4bb01e840.png">

And here's how my build of Matterhorn renders it:
<img width="937" alt="Screen Shot 2022-01-25 at 9 19 37 PM" src="https://user-images.githubusercontent.com/427221/151108117-536a1684-e688-44f8-ae02-5e22198213d9.png">

Looking at the Markdown source, both of these render them as they should: the original markdown source appears exactly as it looks in both images above, and there should be no change in the indentation of "addressing." I do wonder how your web client got a different result! In case it helps, I'm doing this testing on Mattermost 6.0.0 and the `develop` branch of Matterhorn, but the code that is responsible for this in Matterhorn hasn't changed in a long time. In any case, the Matterhorn behavior in your example is correct.

I hope that helps, and I'm going to close this since I don't see a Matterhorn problem. But if you find out more, I'd be curious to know!
