### ISSUE TITLE
Show only unread Channels

### ISSUE THREAD

**Issue by petrich** [matterhorn-chat/matterhorn#757]
Hi There... very great Software... i use it every day.

Is there an option... or shurtcut... to show only unread Channels on the left Sidebar? 

Thank you
Greetings

**Comment by jtdaugherty** [comment]
No, there is not an option for that. Can you say a bit more about why you're wanting this feature? Perhaps there are alternative tips I can provide to help.

**Comment by jtdaugherty** [comment]
@petrich - just pinging you again since this is unresolved.

**Comment by petrich** [comment]
Hi @jtdaugherty   ... Thank You for Your response.

The reason for this feature request is... that we have many Channels (over 50) and it would be nice only see the channels where are new messages.

Greetings

**Comment by jtdaugherty** [comment]
I see, thanks. I know how being in many channels can make it difficult to tell what is unread. I did some exploratory work to see what it would take to implement what you are asking for, and the results were interesting. While it isn't too labor-intensive to support showing only unread channels, the behavior actually leads to a user experience that I think is surprising and maybe not helpful. Suppose you enable this behavior, so that you only see unread channels. The consequence of this is that if you switch channels, then the channel you were just in always disappears from the list once you switch away from it! And furthermore, while you can end up in one last channel that you can't switch away from (since there are no *other* unread channels), if you enable this setting at startup then you can end up with no visible channels at all if none have any unread activity. In some sense this is exactly correct behaviorally, but having tried it out I don't think it makes for a good experience, so I'm not inclined to commit the changes.

With that said, I don't know if you know about the `M-a` keybinding, but if you notice that your channel list indicates that you have unread channels (at the top of the channel sidebar) then you can press `M-a` to switch to the next channel with unread activity. And if you use `M-a` to cycle through all of the unread channels, pressing it one final time will return you to the channel where you started. I hope that helps you deal with this problem!

I also wanted to mention that the next release will have some improvements to the channel list that might make life a bit easier on this front: the channel list is getting scrolling keybindings and a visible scroll bar. That should at least help with understanding how much of the list is off screen at a glance.

**Comment by petrich** [comment]
Mhh oki.

What about "Sorting" ? ... binding to a key.

Sort the Channels  by unread. On the top are then the unreaded channels.

**Comment by jtdaugherty** [comment]
@petrich done! See 90082d79246dc9834679d353ebbbd394af7e4505. That will go out in the next release.

**Comment by petrich** [comment]
wow great, thank You @jtdaugherty  :+1:
