### ISSUE TITLE
Open Message in external $EDITOR

### ISSUE THREAD

**Issue by petrich** [matterhorn-chat/matterhorn#760]
Dear Team

is there any way to open a message (written from some channel members) in the external Editor?

(the internal message viewer is good but sometimes i need the Message in an external Editor like the `vi`)

Thank you

**Comment by jtdaugherty** [comment]
HI @petrich, you mention the internal message *viewer* (`C-s`;`v`), but I'm not sure whether you mean the internal message *editor*. If you are wanting to *edit* a message in your external editor, you can do that now by pressing `M-k`.

**Comment by petrich** [comment]
Hi @jtdaugherty  ... the copy/paste would be full ok, 

but unfortunately not work for me because i'm running matterhorn in a non-X environment, where the copy/paste process not work. (i've tried it already)

Is it possible to implement something like: 

Select message --> `C-s` --> and then ie. `M-e`  (<-- open selected message in $EDITOR)

**Comment by jtdaugherty** [comment]
Can you say a bit more about your use case and why you're wanting this feature?

**Comment by petrich** [comment]
For example... from our bot we get ie. log messages in our channels ... those messages have long or many lines which i have to sort... or email to our ticket system.

With `vi` as `$EDITOR` this is all possible (sorting, searching with `regex`, piping the content to `mail` etc..)
With the internal viewer (which is good for other things) its not possible.

**Comment by jtdaugherty** [comment]
Okay, thanks, that's helpful info.

I thought about this a bit more, and I'm not sure I want to implement it exactly in this way because it raises other questions like 1) what if `EDITOR` isn't set? and 2) what should Matterhorn do once the editor exits? While having the file open in your editor may be what you want, implementing it that way requires that we figure out what else should happen as part of this behavior. But the feature we'd be adding isn't a new way to *edit* Matterhorn messages; it's a way of viewing them only, but using an editor, not a pager, etc. I don't want this feature to seem like a weird ad-hoc thing we added, and all of the answers that I can think of to the two questions I wrote above will still result in this feature seeming like a strange thing to have because it assumes the user has the exact workflow in mind that is motivating your original request.

So I'd like to take a different approach: rather than opening a message directly in the editor -- because it's unclear what to do with the editor's contents once it exits -- I'd like to just add a key binding to *save* a message's raw contents to a file of your choosing. I know that's a bit less direct and would introduce extra steps, but it seems to me that that is what is being asked for here: a way to get the raw message contents out of Matterhorn so they can be used elsewhere.

**Comment by petrich** [comment]
Thank you. That would be also good.

**Comment by jtdaugherty** [comment]
Okay, thanks - I'm glad to hear that would work for you. I'll update here when I have some progress to report!

**Comment by lmoellendorf** [comment]
If you are at it, could you please implement it for multiple messages, so (a part of) the log can be exported to a file? As requested here: https://github.com/matterhorn-chat/matterhorn/issues/686

**Comment by jtdaugherty** [comment]
@lmoellendorf that ticket is closed. Perhaps you meant #583, which is open. In any case, I'm happy to implement the feature we've been discussing here, using the existing message selection functionality for a single message.

**Comment by setharnold** [comment]
Ohh, saving selected messages to files probably could have helped us discussing https://github.com/matterhorn-chat/matterhorn/issues/756

**Comment by petrich** [comment]
Ahh, i see an new release is there @jtdaugherty , great. Is the "save message to file" Feature included? Thank you

**Comment by jtdaugherty** [comment]
@petrich if you are referring to the work associated with this ticket, then no, this ticket has not been implemented yet.

**Comment by jtdaugherty** [comment]
This is now implemented on `develop` using a new `O` keybinding in message selection mode.

**Comment by petrich** [comment]
ahh great... will test ist soon. Thank you very much
