### ISSUE TITLE
Error while typing text

### ISSUE THREAD

**Issue by hectorBouvier** [matterhorn-chat/matterhorn#766]
Using Matterhorn, each time I type a letter in a message, I get :

```
An unexpected error has occurred! The exception encountered was:
  fd:19: hGetLine: invalid argument (invalid byte sequence)
Please report this error at https://github.com/matterhorn-chat/matterhorn/issues
```
This happen on a snap installation of matterhorn, Ubuntu 20.04.4 LTS, connecting to a Mattermost 6.5.0 server.

This doesn't prevent from sending/receiving messages, it's just annoying that a pile of error messages pollutes the channels

**Comment by jtdaugherty** [comment]
Hi @hectorBouvier, thanks for reporting this. Which version of `matterhorn` is this happening on? If it's happening on the latest release, did it happen on the prior release?

**Comment by hectorBouvier** [comment]
Hi @jtdaugherty, The version I'm using is the 50200.15.0 (develop@1257178).
This is my first installation of Matterhorn, so I don't know how other versions behave.

**Comment by jtdaugherty** [comment]
@hectorBouvier it's good to hear that 50200.16.0 resolved the issue for you. This makes me wonder whether the bug is specific to the Snap version of Matterhorn (which is not officially supported). I don't know how Snap packages work, but I'd be curious to know whether you run into this again once 50200.16.0 becomes available via Snap.
