### ISSUE TITLE
quoted code block markdown renders different than I expected

### ISSUE THREAD

**Issue by setharnold** [matterhorn-chat/matterhorn#782]
Hello, I sent a message that combined both markdown `>` quoted content as well as ` ``` ` triple-quoted code block and I think matterhorn may have rendered it differently than the web version, and also differently than I expected.

I'm not actually sure it matters, since it's *all* monospaced anyway, but it is a difference. (The `yank code` command grabbed the URL rather than the text, so it's not entirely about the color and vertical bar.)

GitHub is making it difficult to attach markdown in a comment or in the main body of the issue. Here it is in base64:

```
PmBgYAogICogc2NwKDEpOiBkbyBub3Qgbm90IGZ0cnVuY2F0ZSgzKSBmaWxlcyBlYXJseSB3aGVu
IGluIHNmdHAgbW9kZS4gVGhlCiAgIHByZXZpb3VzIGJlaGF2aW91ciBvZiB1bmNvbmRpdGlvbmFs
bHkgdHJ1bmNhdGluZyB0aGUgZGVzdGluYXRpb24KICAgZmlsZSB3b3VsZCBjYXVzZSAic2NwIH4v
Zm9vIGxvY2FsaG9zdDpmb28iIGFuZCB0aGUgcmV2ZXJzZQogICAic2NwIGxvY2FsaG9zdDpmb28g
fi9mb28iIHRvIGRlbGV0ZSBhbGwgdGhlIGNvbnRlbnRzIG9mIHRoZWlyCiAgIGRlc3RpbmF0aW9u
LiBiejM0MzEKYGBgCgpodHRwczovL3d3dy5vcGVud2FsbC5jb20vbGlzdHMvb3NzLXNlY3VyaXR5
LzIwMjIvMTAvMDQvMQo=
```

Thanks

![markdown](https://user-images.githubusercontent.com/5447148/193957012-256e72b0-ffc8-4a75-b09e-cbb9f55ac3ed.png)
![mattermost](https://user-images.githubusercontent.com/5447148/193957014-298821a5-53e8-4677-ae59-c108070efad6.png)
![matterhorn](https://user-images.githubusercontent.com/5447148/193957016-443ff19b-7b2d-4f97-929e-f6313c35121f.png)

**Comment by jtdaugherty** [comment]
Thanks for opening this. Looking at the screenshots, it appears that Matterhorn's difference is that it actually parses the block quote as a bulleted list and renders it accordingly, which I find surprising. Is that the behavior you are wanting to point out?

**Comment by jtdaugherty** [comment]
Oh! I missed the `>` at the start of the message. So Matterhorn is seeing a blockquote but somehow missing the verbatim markings, it seems. I have no idea whether that's even valid Markdown; I'd have to look. The parser we use should be conformant to the CommonMark spec.

**Comment by jtdaugherty** [comment]
If I use [the reference implementation's testing tool](https://spec.commonmark.org/dingus/) and provide the input above, I get the same thing that Matterhorn parses (which I expect). It would seem that the web client's parser is treating the single `>` as adequate to demarcate the entire verbatim block as a block quote. To get the same result in Matterhorn, `>` needs to be prepended to each line (which I think is probably a better behavior anyway).

I'm inclined to say that the Markdown input text here is not well-formed, but it almost doesn't matter what I think because we don't control the Markdown implementation that we use at a low enough level to make an exception for a behavior like this. For what it's worth, at some point in the past I asked the server developers for Mattermost about whether they'd ever consider using CommonMark as their Markdown implementation in their official clients and I believe the answer was something like "yes, we'd like to get around to that at some point." :/

**Comment by setharnold** [comment]
Hello, thanks for taking a look. After https://github.com/matterhorn-chat/matterhorn/issues/752 I figured it was enough to just mark one line as a quote, and I've been very lazy since then in how I format my messages. :)

(I'd forgotten the reference testing tool from the other issue. That might have saved some time.)

In any event, I can easily understand "it's not worth the trouble to modify the markdown parser" as a motivator to move on. Here's hoping the Mattermost team can migrate to something more .. common .. soon.

Thanks
