### ISSUE TITLE
Small graphical glitsches with emojis

### ISSUE THREAD

**Issue by chrnin** [matterhorn-chat/matterhorn#785]
Hi,

I spotted 2 small glitsches when using emojis.

## channel names
some people use emojis in their channel name (it's pretty ugly but I can't tell them :) ) and it causes little damages to the rendering.it looks like emojis are 2 digits wide but account for only 1 in the side bar, giving a wrong line rendering (the pipe char is 1 char on the right).
Here's an example in gnome-terminal:
![image](https://user-images.githubusercontent.com/36405135/203495858-c4f4f1bf-ba6d-4d56-a540-9789125b9067.png)

## typing in the input bar
When I insert an unicode emoji in the text (with copy paste in my example), the input zone has a strange behaviour, see:
![image](https://user-images.githubusercontent.com/36405135/203496303-8273bf39-53b2-4180-ba46-2ce4ef0f92e6.png)
When I finally send the message, everything gets mixed up
![image](https://user-images.githubusercontent.com/36405135/203496583-334ca267-29db-4517-8ede-dfb58984d084.png)

But everything gets back to normal if I change channel and come back. 

Regards,
Christophe

**Comment by jtdaugherty** [comment]
Hi @chrnin - unfortunately this is a common problem with Unicode emoji. We have [a FAQ entry about it](https://github.com/matterhorn-chat/matterhorn/blob/master/docs/FAQ.md#does-matterhorn-support-graphical-emoji). I'm sorry to say that there is not much we can do about it at the moment. Both of the issues you showed in screenshots are caused by emoji width disagreements between the terminal emulator and Matterhorn. In general, we don't have a good way to ensure that the two are in agreement in every case and new emoji are being added all the time.

**Comment by chrnin** [comment]
Oh ok, I missed this FAQ about emoji, thanks for the explanation ! I thought all emojis were 2 chars wide, but if it's not reliable, there's no way to bother with that. ;) 
Thanks !
