### ISSUE TITLE
Building it from source doesn't require GitHub account

### ISSUE THREAD

**Issue by ajvn** [matterhorn-chat/matterhorn#823]
Hello, I was recently building Matterhorn for Fedora platform, and found this part in the building document:
* https://github.com/matterhorn-chat/matterhorn/blob/master/docs/BUILDING.md?plain=1#L28-L29
```
Before building Matterhorn from source, you'll need a GitHub account. A GitHub account is necessary to fetch the submodule sources.
```
This is not strictly true, as it's possible to edit URLs in `.gitmodules` file and convert them to HTTP, either by editing them manually and then running `git submodule sync` command or by using `git submodule set-url <submodule> <url>`.

Please let me know if this is something you're interested in editing or if I've missed something. If you'd like to update that document, I can do it.

Thank you for the excellent client.

**Comment by jtdaugherty** [comment]
> This is not strictly true, as it's possible to edit URLs in .gitmodules file and convert them to HTTP, either by editing them manually and then running git submodule sync command or by using git submodule set-url <submodule> <url>.

Yes, that's true. The docs say what they say to set expectations to get ahead of people filing tickets saying that the submodules are misconfigured, which has happened. Since we'd prefer to keep the submodules configured as they are, and because users building from source are the exception rather than the rule, I'd like to keep them as they are.

With that said, we've also made the recommendation to update the submodules locally before, so I'd be happy to add that to the build instructions for folks who need to do that for whatever reason.

**Comment by jtdaugherty** [comment]
That's now done in f072b61604610745069060b756c01da4a3a17629.

**Comment by jtdaugherty** [comment]
(Also, in case it matters: the recent release didn't initially provide a Fedora build, but I got that resolved and uploaded a Fedora tarball to the release a few days ago.)

**Comment by ajvn** [comment]
Thanks, it's not a problem for me to build from source, it's quite straightforward process, but I appreciate the effort.

**Comment by jtdaugherty** [comment]
Okay, great! Thanks!
