### ISSUE TITLE
Typo in commonlisp.xml

### ISSUE THREAD

**Issue by christophejunke** [matterhorn-chat/matterhorn#829]
By mere luck I stumbled upon this typo in `commonlisp.xml`

https://github.com/matterhorn-chat/matterhorn/blob/cd2e01009fcb88f9db97bf5984621f761af29959/syntax/commonlisp.xml#L912

I think the fix is to remove `truncase`, as there is no other symbol at this position in the [symbol index](http://clhs.lisp.se/Front/X_AllSym.htm).

**Comment by jtdaugherty** [comment]
Thanks for this report! We use the XML syntax specifications from the Kate project as snapshotted by [skylighting-core](https://hackage.haskell.org/package/skylighting-core), and even looking at their latest files, `truncase` is still there. I don't want to get into the business of maintaining a diff of corrections to those files for Matterhorn, so I'd recommend reporting this on the upstream project. I'd do it myself, but I don't think I can adequately represent the concern here since I don't know whether the upstream XML file intends to support a wider (older) range of Lisp dialects. I wouldn't recommend removing it since it appears in other projects like [this one](https://gemfury.com/akeneo-nagios/deb:vim-runtime/-/content/usr/share/vim/vim81/syntax/lisp.vim) which suggests to me that while it might not be in the symbol list now, it might still appear in the wild in real programs and should therefore be recognized by highlighters that use this XML spec.

I hope that helps!

**Comment by lispm** [comment]
There is no such symbol in Common Lisp, the language, for which this file is a list of symbols. So truncase can be removed.

Common Lisp has a standard with a defined set of symbols. `truncase` was never a symbol.

These are the Common Lisp symbols: https://www.lispworks.com/documentation/HyperSpec/Front/X_AllSym.htm

**Comment by jtdaugherty** [comment]
@lispm Please see my comment above which provides the context for why this is closed. Thanks!

**Comment by dhaumann** [comment]
About to be fixed upstream: https://invent.kde.org/frameworks/syntax-highlighting/-/merge_requests/659

**Comment by jtdaugherty** [comment]
Thank you!
